"""Day 5 — Logistic regression from scratch, and why the coefficients are readable.

A synthetic cohort with known generating coefficients, for the reason
Day 1 generated its own R peaks: on real data the fitted number *is* the
answer and there is nothing to check it against.

The fit recovers them, with error falling as the square root of the
cohort. ``exp(coefficient)`` is then a sentence a clinician can argue
with — a smoker's odds are 2.23 times a non-smoker's — which is most of
why logistic regression is still what clinical risk scores are made of.

Two things qualify that sentence, and both are measured.

**It is about odds.** An odds ratio of 2.23 multiplies a 1% risk by 2.20
and a 60% risk by 1.28. The coefficient does not change; what people hear
does.

**And "holding the others fixed" is doing a lot of work.** I expected
correlated features to split the shared signal arbitrarily. At twenty
thousand patients they do not — collinearity costs variance, not bias.
Draw the study forty times at three hundred patients and the picture
changes: with independent features the age odds ratio lands between 1.31
and 2.64, and with `r = 0.87` between **0.66 and 3.90**. One of those
forty honest studies concludes that age is protective.

The coefficient stays readable. What it stops being is reliable, and the
fitted number does not say which study you are holding.

NOT A MEDICAL DEVICE. Every patient in this repo is generated by it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# --- Day 5 -----------------------------------------------------------------

#: The features of the synthetic cohort, and the coefficients that
#: generated it. Everything in Level 2 is scored against these numbers,
#: for the same reason Day 1 generated its own R peaks: a coefficient
#: estimated from real data can only be compared with somebody else's
#: estimate, and an estimate is not a truth.
TRUE_COEFFICIENTS = {
    "age_decades_over_50": 0.55,
    "systolic_over_120_per_10": 0.35,
    "cholesterol_over_5_per_1": 0.30,
    "smoker": 0.80,
    "diabetic": 0.90,
}

#: With the feature distribution below this gives an event rate near 26%.
#: ``make_cohort`` can solve for a different one - prevalence is the
#: subject of Day 6 and a parameter of Day 7, so it had better be a knob
#: rather than a constant chosen once and described inaccurately.
TRUE_INTERCEPT = -2.6

FEATURE_NAMES = tuple(TRUE_COEFFICIENTS)


@dataclass(frozen=True)
class Cohort:
    """A synthetic patient cohort with a known generating model.

    ``x`` holds the features in ``FEATURE_NAMES`` order, already centred
    on clinically meaningful reference points - age in decades past 50,
    systolic pressure in units of 10 mmHg past 120 - so that a
    coefficient reads as "per decade" rather than "per year" and the
    intercept is the log-odds of a reference patient rather than of a
    newborn with no blood pressure.
    """

    x: np.ndarray
    y: np.ndarray
    risk: np.ndarray
    names: tuple = FEATURE_NAMES

    def __len__(self) -> int:
        return len(self.y)

    @property
    def prevalence(self) -> float:
        return float(self.y.mean())


def sigmoid(z: np.ndarray) -> np.ndarray:
    """1 / (1 + exp(-z)), written so it does not overflow.

    ``exp(800)`` is infinity in float64, and a linear predictor of 800 is
    not unusual once a model is confident. The two-branch form keeps the
    exponent negative on both sides.

    It still **saturates**: this returns exactly 1.0 from z = 37 upward,
    because ``1 + 2.2e-16`` is 1.0 at double precision. Nothing is wrong
    with the arithmetic - the value has simply left the range float64 can
    distinguish from certainty - and it is why ``log_loss`` clips. A
    patient predicted at exactly 1.0 who has no event scores an infinite
    loss, and one of them would make the mean over four thousand patients
    infinite too.

    >>> sigmoid(np.array([0.0])).round(4)
    array([0.5])
    >>> np.isfinite(sigmoid(np.array([-800.0, 800.0]))).all()
    True
    """
    z = np.asarray(z, dtype=float)
    out = np.empty_like(z)
    positive = z >= 0
    out[positive] = 1.0 / (1.0 + np.exp(-z[positive]))
    exponential = np.exp(z[~positive])
    out[~positive] = exponential / (1.0 + exponential)
    return out


def intercept_for_prevalence(prevalence: float, n: int = 20000, seed: int = 0,
                             coefficients: dict | None = None,
                             correlate_cholesterol: float = 0.0) -> float:
    """The intercept that makes the mean true risk equal ``prevalence``.

    Bisection on a large draw. Exists because Day 6 sweeps prevalence and
    Day 7 tunes against it, and hard-coding one intercept and describing
    its consequence from memory is how a comment ends up claiming 12%
    where the data says 26%.
    """
    if not 0 < prevalence < 1:
        raise ValueError(f"prevalence must be in (0,1), got {prevalence}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    features = make_cohort(n=n, seed=seed, coefficients=coefficients,
                           correlate_cholesterol=correlate_cholesterol).x
    linear = features @ weights
    low, high = -20.0, 20.0
    for _ in range(80):
        middle = (low + high) / 2
        if sigmoid(middle + linear).mean() < prevalence:
            low = middle
        else:
            high = middle
    return (low + high) / 2


def make_cohort(n: int = 4000, seed: int = 0,
                coefficients: dict | None = None,
                intercept: float = TRUE_INTERCEPT,
                correlate_cholesterol: float = 0.0,
                prevalence: float | None = None) -> Cohort:
    """Draw patients, compute their true risk, and flip a coin each.

    The outcome is **sampled** from the true risk rather than thresholded
    at it. That distinction is the whole of Day 8: a patient with a 30%
    risk who does not have the event is not a model error, and a dataset
    built by thresholding would make calibration meaningless.

    ``correlate_cholesterol`` makes cholesterol partly a function of age,
    which is true of real cohorts and is what Day 5's last section is
    about.
    """
    if n < 1:
        raise ValueError(f"n must be positive, got {n}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    if prevalence is not None:
        intercept = intercept_for_prevalence(
            prevalence, coefficients=coefficients,
            correlate_cholesterol=correlate_cholesterol)
    rng = np.random.default_rng(seed)

    age_years = rng.normal(58.0, 9.0, size=n)
    age = (age_years - 50.0) / 10.0
    systolic = (rng.normal(132.0, 16.0, size=n) - 120.0) / 10.0
    base_cholesterol = rng.normal(5.4, 1.0, size=n)
    if correlate_cholesterol:
        base_cholesterol = (base_cholesterol
                            + correlate_cholesterol * age * 1.0)
    cholesterol = base_cholesterol - 5.0
    smoker = (rng.random(n) < 0.28).astype(float)
    diabetic = (rng.random(n) < 0.15).astype(float)

    x = np.column_stack([age, systolic, cholesterol, smoker, diabetic])
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    risk = sigmoid(intercept + x @ weights)
    y = (rng.random(n) < risk).astype(float)
    return Cohort(x=x, y=y, risk=risk)


def log_loss(y: np.ndarray, probability: np.ndarray, eps: float = 1e-12) -> float:
    """Mean negative log-likelihood, the thing the fit minimises.

    Clipped away from 0 and 1 because a confident wrong prediction has
    infinite loss, and one such patient would make the whole average
    infinite regardless of the other three thousand nine hundred.
    """
    probability = np.clip(probability, eps, 1 - eps)
    return float(-np.mean(y * np.log(probability)
                          + (1 - y) * np.log(1 - probability)))


def fit_logistic(x: np.ndarray, y: np.ndarray, learning_rate: float = 0.5,
                 iterations: int = 4000, l2: float = 0.0,
                 tolerance: float = 1e-9) -> tuple:
    """Gradient descent on the log-loss. Returns ``(weights, intercept)``.

    The gradient of the log-loss with respect to the linear predictor is
    ``p - y``, which is the same clean form cross-entropy has everywhere
    else - no chain rule through the sigmoid survives into it, because
    the sigmoid's derivative cancels against the log's.

    ``l2`` shrinks the weights towards zero. It is off by default,
    because Day 5's subject is what the coefficients mean and a penalty
    biases them on purpose.
    """
    if learning_rate <= 0:
        raise ValueError(f"learning_rate must be positive, got {learning_rate}")
    if l2 < 0:
        raise ValueError(f"l2 must be non-negative, got {l2}")
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    weights = np.zeros(x.shape[1])
    intercept = 0.0
    previous = float("inf")
    for _ in range(iterations):
        probability = sigmoid(intercept + x @ weights)
        error = probability - y
        gradient = x.T @ error / len(y) + l2 * weights
        intercept -= learning_rate * float(error.mean())
        weights -= learning_rate * gradient
        loss = log_loss(y, probability)
        if abs(previous - loss) < tolerance:
            break
        previous = loss
    return weights, intercept


def predict(x: np.ndarray, weights: np.ndarray, intercept: float) -> np.ndarray:
    """Predicted probability for each row."""
    return sigmoid(intercept + np.asarray(x, dtype=float) @ weights)


def odds_ratio(coefficient: float) -> float:
    """exp(coefficient): the multiplier on the ODDS per unit of the feature.

    The reason a logistic coefficient is quotable at all. A coefficient
    of 0.80 for smoking means a smoker's odds are ``exp(0.80) = 2.23``
    times a non-smoker's, all else equal - which is a sentence a clinician
    can check against their own experience, and a random forest cannot
    produce.

    Note **odds**, not risk. At low risk the two are close; at high risk
    they diverge badly, and the demo shows by how much.

    >>> round(odds_ratio(0.8), 3)
    2.226
    """
    return float(np.exp(coefficient))


def risk_ratio(coefficient: float, baseline_risk: float) -> float:
    """How much the RISK multiplies, which depends on where you start.

    The number people hear when they are told an odds ratio.
    """
    if not 0 < baseline_risk < 1:
        raise ValueError(f"baseline_risk must be in (0,1), got {baseline_risk}")
    baseline_odds = baseline_risk / (1 - baseline_risk)
    new_odds = baseline_odds * np.exp(coefficient)
    new_risk = new_odds / (1 + new_odds)
    return float(new_risk / baseline_risk)


def recovery_error(fitted: np.ndarray, truth: dict | None = None) -> dict:
    """Absolute error between each fitted coefficient and the one used."""
    truth = truth or TRUE_COEFFICIENTS
    return {name: abs(fitted[index] - truth[name])
            for index, name in enumerate(FEATURE_NAMES)}


def coefficient_spread(n: int, correlate_cholesterol: float = 0.0,
                       repeats: int = 40, index: int = 0) -> dict:
    """Refit on many independent cohorts and report the spread of one weight.

    The only honest way to talk about what a coefficient "is" from a
    single study: draw the study again and see what else it might have
    said.
    """
    values = []
    for seed in range(repeats):
        cohort = make_cohort(n=n, seed=seed,
                             correlate_cholesterol=correlate_cholesterol)
        weights, _ = fit_logistic(cohort.x, cohort.y, iterations=4000)
        values.append(weights[index])
    values = np.array(values)
    return {"mean": float(values.mean()), "sd": float(values.std()),
            "min": float(values.min()), "max": float(values.max())}


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every patient here is generated by this file.")
    print()

    cohort = make_cohort(n=4000, seed=0)
    print(f"cohort: {len(cohort)} patients, prevalence {cohort.prevalence:.1%}, "
          f"true risk {cohort.risk.min():.1%} to {cohort.risk.max():.1%}")
    print("the outcome is SAMPLED from each patient's true risk, not")
    print("thresholded at it - a 30% patient without the event is not an")
    print("error, and Day 8 depends on that distinction existing.")

    print()
    print("=" * 72)
    print("1. the fit recovers the coefficients it was generated from")
    print("=" * 72)
    weights, intercept = fit_logistic(cohort.x, cohort.y)
    print(f"  {'feature':<30}{'true':>8}{'fitted':>9}{'error':>8}{'odds ratio':>12}")
    for index, name in enumerate(FEATURE_NAMES):
        truth = TRUE_COEFFICIENTS[name]
        print(f"  {name:<30}{truth:>8.2f}{weights[index]:>9.2f}"
              f"{abs(weights[index] - truth):>8.2f}{odds_ratio(weights[index]):>12.2f}")
    print(f"  {'intercept':<30}{TRUE_INTERCEPT:>8.2f}{intercept:>9.2f}"
          f"{abs(intercept - TRUE_INTERCEPT):>8.2f}")
    print()
    print("  and the error shrinks as the cohort grows - averaged over ten")
    print("  cohorts per size, because a single draw is not monotone:")
    print(f"    {'n':>7}{'mean |error|':>15}{'worst seen':>13}")
    for size in (500, 2000, 8000, 32000):
        averages, worst = [], 0.0
        for seed in range(10):
            drawn = make_cohort(n=size, seed=seed)
            errors = recovery_error(fit_logistic(drawn.x, drawn.y)[0])
            averages.append(np.mean(list(errors.values())))
            worst = max(worst, max(errors.values()))
        print(f"    {size:>7}{np.mean(averages):>15.3f}{worst:>13.3f}")
    print()
    print("  that is the whole argument for a synthetic cohort. On real data")
    print("  the fitted number IS the answer and there is nothing to compare")
    print("  it against - the same reason Day 1 generated its own R peaks.")

    print()
    print("=" * 72)
    print("2. why the coefficients are readable")
    print("=" * 72)
    print("  exp(coefficient) is the multiplier on the ODDS, holding the")
    print("  other features fixed. It is a sentence a clinician can check:")
    print()
    for name in ("smoker", "diabetic", "age_decades_over_50"):
        coefficient = TRUE_COEFFICIENTS[name]
        print(f"    {name:<26} odds x {odds_ratio(coefficient):.2f}")
    print()
    print("  no tree ensemble produces that sentence, and it is most of the")
    print("  reason logistic regression is still what clinical risk scores")
    print("  are made of.")
    print()
    print("  but 'the odds double' is heard as 'the risk doubles', and those")
    print("  are the same statement only when the risk is small:")
    print()
    print(f"    {'baseline risk':>14}{'odds ratio':>12}{'risk ratio':>12}")
    for baseline in (0.01, 0.05, 0.12, 0.30, 0.60):
        print(f"    {baseline:>14.0%}{odds_ratio(0.8):>12.2f}"
              f"{risk_ratio(0.8, baseline):>12.2f}")
    print()
    print("  a smoking odds ratio of 2.23 multiplies a 1% risk by 2.20 and a")
    print("  60% risk by 1.28. The coefficient did not change; the sentence")
    print("  people hear did.")

    print()
    print("=" * 72)
    print("3. what 'readable' actually requires")
    print("=" * 72)
    print("  cholesterol rises with age in any real cohort. Make it do so")
    print("  here and refit - the coefficients barely move:")
    print()
    print(f"  {'correlation':>12}{'r(age,chol)':>13}{'age':>8}{'chol':>8}{'sum':>8}")
    for rho in (0.0, 0.6, 1.0, 2.0):
        correlated = make_cohort(n=20000, seed=0, correlate_cholesterol=rho)
        observed = float(np.corrcoef(correlated.x[:, 0], correlated.x[:, 2])[0, 1])
        fitted, _ = fit_logistic(correlated.x, correlated.y, iterations=6000)
        print(f"  {rho:>12.1f}{observed:>13.2f}{fitted[0]:>8.2f}{fitted[2]:>8.2f}"
              f"{fitted[0] + fitted[2]:>8.2f}")
    print(f"  {'true':>12}{'':>13}{TRUE_COEFFICIENTS['age_decades_over_50']:>8.2f}"
          f"{TRUE_COEFFICIENTS['cholesterol_over_5_per_1']:>8.2f}"
          f"{TRUE_COEFFICIENTS['age_decades_over_50'] + TRUE_COEFFICIENTS['cholesterol_over_5_per_1']:>8.2f}")
    print()
    print("  I expected the model to split the shared signal arbitrarily")
    print("  between two correlated features. At twenty thousand patients it")
    print("  does not - collinearity costs variance, not bias, and twenty")
    print("  thousand patients is enough to pay it.")
    print()
    print("  so draw the study again, forty times, and look at the SPREAD:")
    print()
    print(f"  {'n':>6}{'features':>14}{'mean':>8}{'sd':>8}{'min':>8}{'max':>8}")
    for size in (300, 1000, 5000):
        for label, rho in (("independent", 0.0), ("r = 0.87", 2.0)):
            spread = coefficient_spread(size, correlate_cholesterol=rho, repeats=20)
            print(f"  {size:>6}{label:>14}{spread['mean']:>8.2f}{spread['sd']:>8.2f}"
                  f"{spread['min']:>8.2f}{spread['max']:>8.2f}")
    print()
    print("  the mean is right in every row. The standard deviation is two")
    print("  to three times larger under correlation, at every size.")
    print()
    print("  and here is what that means for one study of three hundred:")
    print()
    print(f"  {'features':<16}{'coefficient range':>22}{'odds ratio range':>22}")
    for label, rho in (("independent", 0.0), ("r = 0.87", 2.0)):
        spread = coefficient_spread(300, correlate_cholesterol=rho, repeats=40)
        print(f"  {label:<16}"
              f"{f'''{spread['min']:.2f} to {spread['max']:.2f}''':>22}"
              f"{f'''{odds_ratio(spread['min']):.2f} to {odds_ratio(spread['max']):.2f}''':>22}")
    print(f"  {'the truth':<16}{0.55:>22.2f}{odds_ratio(0.55):>22.2f}")
    print()
    print("  with correlated features, forty honest studies of the same")
    print("  population report age odds ratios from 0.66 to 3.90. One of")
    print("  them concludes that age is PROTECTIVE.")
    print()
    print("  the coefficient is still readable. What it is no longer is")
    print("  reliable, and nothing in the fitted number says which of those")
    print("  two studies you are holding.")

    print()
    print("=" * 72)
    print("what this day establishes")
    print("=" * 72)
    print("  logistic regression is worth its place in clinical scoring")
    print("  because exp(coefficient) is a sentence somebody can argue with.")
    print()
    print("  the sentence is only worth as much as the cohort behind it:")
    print("    - it is about ODDS, which stop resembling risk above about 10%")
    print("    - it assumes the other features are held fixed, which")
    print("      correlated features make a counterfactual nobody can check")
    print("    - and its uncertainty is invisible in the number itself")
    print()
    print("  Day 6 stops asking what the model says and starts asking how")
    print("  often it is right - where prevalence does to accuracy what")
    print("  baseline risk did to the odds ratio here.")
