"""Day 6 — Beyond accuracy: sensitivity, specificity, PPV, and prevalence.

Day 5's cohort has a prevalence knob, so the same model can be refitted
on populations differing only in how common the event is. The result is
the sharpest form of an old argument.

**At 0.9% prevalence the model scores 99.1% accuracy and finds zero
cases** — which is exactly what a model answering "no" to everybody
scores, to one decimal place. Accuracy is not a weak measure here. It is
measuring the prevalence and reporting it as performance.

The model is not the problem. Its AUC is 0.73-0.76 at every prevalence,
because AUC is a ranking measure that never looks at a threshold; flag
the top k patients and real sensitivity comes back. Which is also AUC's
limitation: it is identical for a model that is useful in your clinic and
one that is not, since what differs is the threshold and the population,
and AUC ignores both by construction.

And holding a test fixed at 95% sensitivity and 95% specificity, its PPV
runs from 95% down to **1.9%** as prevalence falls to one in a thousand —
fifty-three false alarms for every case. Sensitivity and specificity are
properties of the test, measured on diseased and well patients
separately. PPV is Bayes' rule applied to both, and a paper reporting
only the first two has said nothing about what a positive result means
where you work.

NOT A MEDICAL DEVICE. Every patient in this repo is generated by it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# --- Day 5 -----------------------------------------------------------------

#: The features of the synthetic cohort, and the coefficients that
#: generated it. Everything in Level 2 is scored against these numbers,
#: for the same reason Day 1 generated its own R peaks: a coefficient
#: estimated from real data can only be compared with somebody else's
#: estimate, and an estimate is not a truth.
TRUE_COEFFICIENTS = {
    "age_decades_over_50": 0.55,
    "systolic_over_120_per_10": 0.35,
    "cholesterol_over_5_per_1": 0.30,
    "smoker": 0.80,
    "diabetic": 0.90,
}

#: With the feature distribution below this gives an event rate near 26%.
#: ``make_cohort`` can solve for a different one - prevalence is the
#: subject of Day 6 and a parameter of Day 7, so it had better be a knob
#: rather than a constant chosen once and described inaccurately.
TRUE_INTERCEPT = -2.6

FEATURE_NAMES = tuple(TRUE_COEFFICIENTS)


@dataclass(frozen=True)
class Cohort:
    """A synthetic patient cohort with a known generating model.

    ``x`` holds the features in ``FEATURE_NAMES`` order, already centred
    on clinically meaningful reference points - age in decades past 50,
    systolic pressure in units of 10 mmHg past 120 - so that a
    coefficient reads as "per decade" rather than "per year" and the
    intercept is the log-odds of a reference patient rather than of a
    newborn with no blood pressure.
    """

    x: np.ndarray
    y: np.ndarray
    risk: np.ndarray
    names: tuple = FEATURE_NAMES

    def __len__(self) -> int:
        return len(self.y)

    @property
    def prevalence(self) -> float:
        return float(self.y.mean())


def sigmoid(z: np.ndarray) -> np.ndarray:
    """1 / (1 + exp(-z)), written so it does not overflow.

    ``exp(800)`` is infinity in float64, and a linear predictor of 800 is
    not unusual once a model is confident. The two-branch form keeps the
    exponent negative on both sides.

    It still **saturates**: this returns exactly 1.0 from z = 37 upward,
    because ``1 + 2.2e-16`` is 1.0 at double precision. Nothing is wrong
    with the arithmetic - the value has simply left the range float64 can
    distinguish from certainty - and it is why ``log_loss`` clips. A
    patient predicted at exactly 1.0 who has no event scores an infinite
    loss, and one of them would make the mean over four thousand patients
    infinite too.

    >>> sigmoid(np.array([0.0])).round(4)
    array([0.5])
    >>> np.isfinite(sigmoid(np.array([-800.0, 800.0]))).all()
    True
    """
    z = np.asarray(z, dtype=float)
    out = np.empty_like(z)
    positive = z >= 0
    out[positive] = 1.0 / (1.0 + np.exp(-z[positive]))
    exponential = np.exp(z[~positive])
    out[~positive] = exponential / (1.0 + exponential)
    return out


def intercept_for_prevalence(prevalence: float, n: int = 20000, seed: int = 0,
                             coefficients: dict | None = None,
                             correlate_cholesterol: float = 0.0) -> float:
    """The intercept that makes the mean true risk equal ``prevalence``.

    Bisection on a large draw. Exists because Day 6 sweeps prevalence and
    Day 7 tunes against it, and hard-coding one intercept and describing
    its consequence from memory is how a comment ends up claiming 12%
    where the data says 26%.
    """
    if not 0 < prevalence < 1:
        raise ValueError(f"prevalence must be in (0,1), got {prevalence}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    features = make_cohort(n=n, seed=seed, coefficients=coefficients,
                           correlate_cholesterol=correlate_cholesterol).x
    linear = features @ weights
    low, high = -20.0, 20.0
    for _ in range(80):
        middle = (low + high) / 2
        if sigmoid(middle + linear).mean() < prevalence:
            low = middle
        else:
            high = middle
    return (low + high) / 2


def make_cohort(n: int = 4000, seed: int = 0,
                coefficients: dict | None = None,
                intercept: float = TRUE_INTERCEPT,
                correlate_cholesterol: float = 0.0,
                prevalence: float | None = None) -> Cohort:
    """Draw patients, compute their true risk, and flip a coin each.

    The outcome is **sampled** from the true risk rather than thresholded
    at it. That distinction is the whole of Day 8: a patient with a 30%
    risk who does not have the event is not a model error, and a dataset
    built by thresholding would make calibration meaningless.

    ``correlate_cholesterol`` makes cholesterol partly a function of age,
    which is true of real cohorts and is what Day 5's last section is
    about.
    """
    if n < 1:
        raise ValueError(f"n must be positive, got {n}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    if prevalence is not None:
        intercept = intercept_for_prevalence(
            prevalence, coefficients=coefficients,
            correlate_cholesterol=correlate_cholesterol)
    rng = np.random.default_rng(seed)

    age_years = rng.normal(58.0, 9.0, size=n)
    age = (age_years - 50.0) / 10.0
    systolic = (rng.normal(132.0, 16.0, size=n) - 120.0) / 10.0
    base_cholesterol = rng.normal(5.4, 1.0, size=n)
    if correlate_cholesterol:
        base_cholesterol = (base_cholesterol
                            + correlate_cholesterol * age * 1.0)
    cholesterol = base_cholesterol - 5.0
    smoker = (rng.random(n) < 0.28).astype(float)
    diabetic = (rng.random(n) < 0.15).astype(float)

    x = np.column_stack([age, systolic, cholesterol, smoker, diabetic])
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    risk = sigmoid(intercept + x @ weights)
    y = (rng.random(n) < risk).astype(float)
    return Cohort(x=x, y=y, risk=risk)


def log_loss(y: np.ndarray, probability: np.ndarray, eps: float = 1e-12) -> float:
    """Mean negative log-likelihood, the thing the fit minimises.

    Clipped away from 0 and 1 because a confident wrong prediction has
    infinite loss, and one such patient would make the whole average
    infinite regardless of the other three thousand nine hundred.
    """
    probability = np.clip(probability, eps, 1 - eps)
    return float(-np.mean(y * np.log(probability)
                          + (1 - y) * np.log(1 - probability)))


def fit_logistic(x: np.ndarray, y: np.ndarray, learning_rate: float = 0.5,
                 iterations: int = 4000, l2: float = 0.0,
                 tolerance: float = 1e-9) -> tuple:
    """Gradient descent on the log-loss. Returns ``(weights, intercept)``.

    The gradient of the log-loss with respect to the linear predictor is
    ``p - y``, which is the same clean form cross-entropy has everywhere
    else - no chain rule through the sigmoid survives into it, because
    the sigmoid's derivative cancels against the log's.

    ``l2`` shrinks the weights towards zero. It is off by default,
    because Day 5's subject is what the coefficients mean and a penalty
    biases them on purpose.
    """
    if learning_rate <= 0:
        raise ValueError(f"learning_rate must be positive, got {learning_rate}")
    if l2 < 0:
        raise ValueError(f"l2 must be non-negative, got {l2}")
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    weights = np.zeros(x.shape[1])
    intercept = 0.0
    previous = float("inf")
    for _ in range(iterations):
        probability = sigmoid(intercept + x @ weights)
        error = probability - y
        gradient = x.T @ error / len(y) + l2 * weights
        intercept -= learning_rate * float(error.mean())
        weights -= learning_rate * gradient
        loss = log_loss(y, probability)
        if abs(previous - loss) < tolerance:
            break
        previous = loss
    return weights, intercept


def predict(x: np.ndarray, weights: np.ndarray, intercept: float) -> np.ndarray:
    """Predicted probability for each row."""
    return sigmoid(intercept + np.asarray(x, dtype=float) @ weights)


def odds_ratio(coefficient: float) -> float:
    """exp(coefficient): the multiplier on the ODDS per unit of the feature.

    The reason a logistic coefficient is quotable at all. A coefficient
    of 0.80 for smoking means a smoker's odds are ``exp(0.80) = 2.23``
    times a non-smoker's, all else equal - which is a sentence a clinician
    can check against their own experience, and a random forest cannot
    produce.

    Note **odds**, not risk. At low risk the two are close; at high risk
    they diverge badly, and the demo shows by how much.

    >>> round(odds_ratio(0.8), 3)
    2.226
    """
    return float(np.exp(coefficient))


def risk_ratio(coefficient: float, baseline_risk: float) -> float:
    """How much the RISK multiplies, which depends on where you start.

    The number people hear when they are told an odds ratio.
    """
    if not 0 < baseline_risk < 1:
        raise ValueError(f"baseline_risk must be in (0,1), got {baseline_risk}")
    baseline_odds = baseline_risk / (1 - baseline_risk)
    new_odds = baseline_odds * np.exp(coefficient)
    new_risk = new_odds / (1 + new_odds)
    return float(new_risk / baseline_risk)


def recovery_error(fitted: np.ndarray, truth: dict | None = None) -> dict:
    """Absolute error between each fitted coefficient and the one used."""
    truth = truth or TRUE_COEFFICIENTS
    return {name: abs(fitted[index] - truth[name])
            for index, name in enumerate(FEATURE_NAMES)}


def coefficient_spread(n: int, correlate_cholesterol: float = 0.0,
                       repeats: int = 40, index: int = 0) -> dict:
    """Refit on many independent cohorts and report the spread of one weight.

    The only honest way to talk about what a coefficient "is" from a
    single study: draw the study again and see what else it might have
    said.
    """
    values = []
    for seed in range(repeats):
        cohort = make_cohort(n=n, seed=seed,
                             correlate_cholesterol=correlate_cholesterol)
        weights, _ = fit_logistic(cohort.x, cohort.y, iterations=4000)
        values.append(weights[index])
    values = np.array(values)
    return {"mean": float(values.mean()), "sd": float(values.std()),
            "min": float(values.min()), "max": float(values.max())}


# --- Day 6 -----------------------------------------------------------------


@dataclass(frozen=True)
class Confusion:
    """The four counts everything else on this day is arithmetic over."""

    true_positive: int
    false_positive: int
    true_negative: int
    false_negative: int

    @property
    def total(self) -> int:
        return (self.true_positive + self.false_positive
                + self.true_negative + self.false_negative)

    @property
    def positives(self) -> int:
        return self.true_positive + self.false_negative

    @property
    def prevalence(self) -> float:
        return self.positives / self.total if self.total else 0.0


def confusion(y: np.ndarray, predicted: np.ndarray) -> Confusion:
    """Count the four outcomes.

    >>> confusion(np.array([1, 0]), np.array([1, 1])).false_positive
    1
    """
    y = np.asarray(y).astype(bool)
    predicted = np.asarray(predicted).astype(bool)
    return Confusion(
        true_positive=int(np.sum(y & predicted)),
        false_positive=int(np.sum(~y & predicted)),
        true_negative=int(np.sum(~y & ~predicted)),
        false_negative=int(np.sum(y & ~predicted)),
    )


def accuracy(matrix: Confusion) -> float:
    """Fraction of patients classified correctly.

    The number that sounds like it answers the question and does not.
    A model predicting "no event" for everyone scores ``1 - prevalence``,
    which at a 5% event rate is 95% - and the demo shows what that model
    is worth.
    """
    if not matrix.total:
        return 0.0
    return (matrix.true_positive + matrix.true_negative) / matrix.total


def sensitivity(matrix: Confusion) -> float:
    """Of the patients who had the event, the fraction found.

    A property of the test on diseased patients only, so it does not
    move when prevalence does. Also called recall.
    """
    if not matrix.positives:
        return 0.0
    return matrix.true_positive / matrix.positives


def specificity(matrix: Confusion) -> float:
    """Of the patients who did not, the fraction correctly cleared."""
    negatives = matrix.true_negative + matrix.false_positive
    if not negatives:
        return 0.0
    return matrix.true_negative / negatives


def ppv(matrix: Confusion) -> float:
    """Of the patients flagged, the fraction who really had the event.

    The number the patient in front of you actually cares about, and the
    only one of the four that **depends on prevalence**. The same test,
    unchanged, has a different PPV in a screening clinic than in a
    referral centre, and that is not a flaw in the test.
    """
    flagged = matrix.true_positive + matrix.false_positive
    if not flagged:
        return 0.0
    return matrix.true_positive / flagged


def npv(matrix: Confusion) -> float:
    """Of the patients cleared, the fraction who really were well."""
    cleared = matrix.true_negative + matrix.false_negative
    if not cleared:
        return 0.0
    return matrix.true_negative / cleared


def ppv_from_rates(sensitivity_value: float, specificity_value: float,
                   prevalence: float) -> float:
    """PPV computed from the two stable rates and the prevalence.

    Bayes' rule, and the cleanest statement of the day: sensitivity and
    specificity are properties of the test, prevalence is a property of
    the population, and **PPV is a property of both**. A paper reporting
    only the first two has told you nothing about what a positive result
    means in your clinic.

    >>> round(ppv_from_rates(0.95, 0.95, 0.01), 4)
    0.1610
    """
    for name, value in (("sensitivity", sensitivity_value),
                        ("specificity", specificity_value),
                        ("prevalence", prevalence)):
        if not 0 <= value <= 1:
            raise ValueError(f"{name} must be between 0 and 1, got {value}")
    true_positive = sensitivity_value * prevalence
    false_positive = (1 - specificity_value) * (1 - prevalence)
    if true_positive + false_positive == 0:
        return 0.0
    return true_positive / (true_positive + false_positive)


def false_alarms_per_case(sensitivity_value: float, specificity_value: float,
                          prevalence: float) -> float:
    """How many people are wrongly flagged for each one correctly flagged.

    The same fact as PPV, in the unit a clinic feels: every one of these
    is a person who gets a phone call, an appointment and a week of worry
    for nothing.
    """
    value = ppv_from_rates(sensitivity_value, specificity_value, prevalence)
    if value <= 0:
        return float("inf")
    return (1 - value) / value


def number_needed_to_screen(sensitivity_value: float, prevalence: float) -> float:
    """Patients screened per true case found."""
    if prevalence <= 0 or sensitivity_value <= 0:
        return float("inf")
    return 1.0 / (prevalence * sensitivity_value)


def always_negative_accuracy(prevalence: float) -> float:
    """The accuracy of predicting "no event" for everybody.

    The baseline every accuracy figure has to beat before it means
    anything, and the one most papers do not print.
    """
    return 1.0 - prevalence


def report(y: np.ndarray, predicted: np.ndarray) -> dict:
    """Every rate at once, from one set of predictions."""
    matrix = confusion(y, predicted)
    return {"accuracy": accuracy(matrix), "sensitivity": sensitivity(matrix),
            "specificity": specificity(matrix), "ppv": ppv(matrix),
            "npv": npv(matrix), "prevalence": matrix.prevalence,
            "flagged": matrix.true_positive + matrix.false_positive}


def auc(y: np.ndarray, score: np.ndarray) -> float:
    """Probability that a random case outranks a random control.

    A **ranking** measure, so it never looks at the threshold. That makes
    it the one number on this day that does not move when prevalence
    does - and also the one that cannot tell you what a positive result
    means for the patient in front of you.

    >>> round(auc(np.array([0, 0, 1, 1]), np.array([0.1, 0.2, 0.3, 0.4])), 3)
    1.0
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    positives, negatives = float(y.sum()), float((1 - y).sum())
    if positives == 0 or negatives == 0:
        return 0.5
    order = np.argsort(score)
    ranks = np.empty(len(score), dtype=float)
    ranks[order] = np.arange(1, len(score) + 1)
    return float((ranks[y == 1].sum() - positives * (positives + 1) / 2)
                 / (positives * negatives))


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every patient here is generated by this file.")

    print()
    print("=" * 74)
    print("1. the same model, five populations")
    print("=" * 74)
    print("  one model, refitted on cohorts that differ only in how common")
    print("  the event is, classified at the obvious threshold of 0.5:")
    print()
    print(f"  {'prevalence':>11}{'accuracy':>10}{'sens':>8}{'spec':>8}"
          f"{'PPV':>8}{'always-no':>12}")
    for target in (0.01, 0.05, 0.12, 0.26, 0.40):
        cohort = make_cohort(n=40000, seed=0, prevalence=target)
        weights, intercept = fit_logistic(cohort.x, cohort.y)
        scores = report(cohort.y, predict(cohort.x, weights, intercept) > 0.5)
        print(f"  {cohort.prevalence:>11.1%}{scores['accuracy']:>10.1%}"
              f"{scores['sensitivity']:>8.1%}{scores['specificity']:>8.1%}"
              f"{scores['ppv']:>8.1%}"
              f"{always_negative_accuracy(cohort.prevalence):>12.1%}")
    print()
    print("  read the first and last columns together. At 0.9% prevalence the")
    print("  model scores 99.1% accuracy and finds ZERO cases - which is")
    print("  exactly what a model answering 'no' to everybody scores, to one")
    print("  decimal place.")
    print()
    print("  accuracy is not a weak measure here. It is measuring the")
    print("  prevalence and reporting it as performance.")

    print()
    print("=" * 74)
    print("2. is the model bad, or is the threshold?")
    print("=" * 74)
    print(f"  {'prevalence':>11}{'AUC':>8}{'sens @0.5':>12}"
          f"{'sens @top-k':>13}{'PPV @top-k':>12}")
    for target in (0.01, 0.05, 0.12, 0.26):
        cohort = make_cohort(n=40000, seed=0, prevalence=target)
        weights, intercept = fit_logistic(cohort.x, cohort.y)
        probability = predict(cohort.x, weights, intercept)
        at_half = report(cohort.y, probability > 0.5)
        cut = float(np.quantile(probability, 1 - cohort.prevalence))
        at_top = report(cohort.y, probability > cut)
        print(f"  {cohort.prevalence:>11.1%}{auc(cohort.y, probability):>8.3f}"
              f"{at_half['sensitivity']:>12.1%}{at_top['sensitivity']:>13.1%}"
              f"{at_top['ppv']:>12.1%}")
    print()
    print("  the AUC barely moves. It is a ranking measure - the probability")
    print("  that a random case scores above a random control - so it never")
    print("  looks at a threshold and never notices prevalence.")
    print()
    print("  the model was never the problem. Flagging the top k patients,")
    print("  where k is the number of cases, recovers real sensitivity at")
    print("  every prevalence. Day 7 is about choosing that k.")
    print()
    print("  which also means AUC cannot be the whole answer: it is identical")
    print("  for a model that is useful in your clinic and one that is not,")
    print("  because what differs between them is the threshold and the")
    print("  population, and AUC has been carefully built to ignore both.")

    print()
    print("=" * 74)
    print("3. PPV is a property of the population, not of the test")
    print("=" * 74)
    print("  hold the test fixed at 95% sensitivity and 95% specificity -")
    print("  numbers any paper would be pleased to report - and vary only")
    print("  the population it is used in:")
    print()
    print(f"  {'prevalence':>11}{'PPV':>9}{'NPV':>9}"
          f"{'false alarms per case':>24}{'screened per case':>19}")
    for prevalence in (0.001, 0.01, 0.05, 0.12, 0.30, 0.50):
        value = ppv_from_rates(0.95, 0.95, prevalence)
        negative = ((0.95 * (1 - prevalence))
                    / (0.95 * (1 - prevalence) + 0.05 * prevalence))
        print(f"  {prevalence:>11.1%}{value:>9.1%}{negative:>9.1%}"
              f"{false_alarms_per_case(0.95, 0.95, prevalence):>24.1f}"
              f"{number_needed_to_screen(0.95, prevalence):>19.1f}")
    print()
    print("  at one in a thousand, a 95/95 test flags fifty-three people for")
    print("  every one it is right about. The test has not changed. Nothing")
    print("  about it has got worse.")
    print()
    print("  sensitivity and specificity are properties of the TEST, measured")
    print("  on diseased and well patients separately, so neither moves with")
    print("  prevalence. PPV is Bayes' rule applied to both, and a paper")
    print("  reporting only the first two has said nothing about what a")
    print("  positive result means in your clinic.")

    print()
    print("=" * 74)
    print("4. what each number is for")
    print("=" * 74)
    print("  accuracy      almost nothing. It tracks prevalence, and the")
    print("                baseline it must beat - always answering 'no' -")
    print("                is rarely printed beside it.")
    print()
    print("  sensitivity   a property of the test. Ask it when a miss is the")
    print("                expensive error: the patient goes home undiagnosed.")
    print()
    print("  specificity   a property of the test. Ask it when a false alarm")
    print("                is the expensive error: the biopsy, the anxiety.")
    print()
    print("  PPV           what a flagged patient should be told, and the")
    print("                only one that changes when you move the same test")
    print("                to a different clinic.")
    print()
    print("  NPV           what a cleared patient should be told. Comfortable")
    print("                at low prevalence for the same reason PPV is not.")
    print()
    print("  AUC           the model's ranking, independent of threshold and")
    print("                prevalence - which is its strength and the precise")
    print("                reason it cannot answer a clinical question.")
    print()
    print("  Day 7 stops treating 0.5 as given, and picks a threshold by")
    print("  deciding which error you would rather make.")
