"""Day 2 — Noise: baseline wander, mains hum, motion artefact.

Day 1 built a signal with exact ground truth. This adds the four things
that ruin a real recording, and measures what each costs a detector.

The central result is that **signal-to-noise ratio does not predict
damage**. Tuned so that every artefact contributes identical noise power,
a naive threshold detector scores 50% precision under mains hum and 80%
under baseline wander — and at -5 dB the spread runs from 28% to 65%. SNR
is out by more than a factor of two.

The ordering is also not the intuitive one. Mains hum and sensor noise,
the two easiest to filter, do *more* damage than motion artefact, which
no filter can touch: a burst is confined to a few hundred milliseconds
while hum is present at every sample. I had that backwards before the
equal-SNR table was run, and the ``motion_artefact`` docstring says so.

One more thing worth separating: sensitivity never moves. Noise adds
energy, so the real beats stay above the line and every failure here is a
false positive. "The detector is 100% sensitive" is true under all four
artefacts and says nothing at all.

NOT A MEDICAL DEVICE. Every signal in this repo is generated by it.
"""

from __future__ import annotations

import numpy as np

# --- reused from day01 -----------------------------------------------------
# Byte-identical to 01_biosignals/day01_synthetic_ecg/ecg.py.



#: Typical adult resting heart rate, in beats per minute.
DEFAULT_BPM = 72.0

#: Sampling rate in Hz. 250 is a common clinical monitor rate and is
#: comfortably above the Nyquist limit for the ~40 Hz content of a QRS.
DEFAULT_FS = 250.0


def _gaussian(t: np.ndarray, centre: float, width: float, height: float) -> np.ndarray:
    """One smooth bump, used for each of the P, Q, R, S and T deflections."""
    return height * np.exp(-0.5 * ((t - centre) / width) ** 2)


def beat_waveform(fs: float = DEFAULT_FS, duration: float = 0.8) -> np.ndarray:
    """One cardiac cycle, as a sum of five Gaussians.

    The parameters below are shaped to look like lead II: a small upright
    P, a sharp tall R flanked by small negative Q and S, and a broad
    low T. Amplitudes are in millivolts.

    The R peak sits at ``0.25 * duration`` deliberately, leaving room for
    the P wave before it. Day 4's detector must not assume that position.

    >>> wave = beat_waveform(fs=250.0, duration=0.8)
    >>> len(wave)
    200
    """
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if duration <= 0:
        raise ValueError(f"duration must be positive, got {duration}")

    samples = int(round(fs * duration))
    t = np.linspace(0.0, duration, samples, endpoint=False)
    r_time = 0.25 * duration

    wave = np.zeros(samples)
    wave += _gaussian(t, r_time - 0.16, 0.025, 0.12)   # P wave
    wave += _gaussian(t, r_time - 0.02, 0.008, -0.16)  # Q
    wave += _gaussian(t, r_time, 0.010, 1.20)          # R
    wave += _gaussian(t, r_time + 0.02, 0.008, -0.28)  # S
    wave += _gaussian(t, r_time + 0.18, 0.045, 0.30)   # T wave
    return wave


def synthesise_ecg(
    duration: float = 10.0,
    bpm: float = DEFAULT_BPM,
    fs: float = DEFAULT_FS,
    hrv: float = 0.0,
    seed: int = 0,
) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(signal, r_peak_samples)``.

    ``hrv`` is the standard deviation of beat-to-beat interval jitter, in
    seconds. At 0 the rhythm is metronomic, which is unphysiological — a
    real heart never is — so Day 4 uses a non-zero value and Day 1 keeps
    both available to show the difference.

    The returned peak positions are **ground truth**, not an estimate.
    Everything downstream is scored against them.

    >>> signal, peaks = synthesise_ecg(duration=4.0, bpm=60.0, fs=100.0)
    >>> len(signal), len(peaks)
    (400, 4)
    """
    if duration <= 0:
        raise ValueError(f"duration must be positive, got {duration}")
    if bpm <= 0:
        raise ValueError(f"bpm must be positive, got {bpm}")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if hrv < 0:
        raise ValueError(f"hrv must be non-negative, got {hrv}")

    rng = np.random.default_rng(seed)
    total_samples = int(round(duration * fs))
    signal = np.zeros(total_samples)
    peaks: list[int] = []

    mean_interval = 60.0 / bpm
    beat = beat_waveform(fs=fs, duration=mean_interval)
    r_offset = int(round(0.25 * len(beat)))

    time = 0.0
    while True:
        start = int(round(time * fs))
        if start >= total_samples:
            break
        end = min(start + len(beat), total_samples)
        signal[start:end] += beat[: end - start]
        r_position = start + r_offset
        if r_position < total_samples:
            peaks.append(r_position)

        interval = mean_interval
        if hrv > 0:
            interval = max(0.25, mean_interval + rng.normal(0.0, hrv))
        time += interval

    return signal, np.array(peaks, dtype=int)


def heart_rate(peaks: np.ndarray, fs: float = DEFAULT_FS) -> float:
    """Mean heart rate in beats per minute, from R-peak positions.

    Computed from the **intervals**, not from ``len(peaks) / duration``.
    The two differ whenever the recording does not start and end exactly
    on a beat, and the interval form is what a monitor actually reports.

    >>> round(heart_rate(np.array([0, 250, 500, 750]), fs=250.0), 3)
    60.0
    """
    peaks = np.asarray(peaks)
    if peaks.size < 2:
        raise ValueError("need at least two peaks to measure a rate")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    intervals = np.diff(peaks) / fs
    return float(60.0 / intervals.mean())


def rr_intervals(peaks: np.ndarray, fs: float = DEFAULT_FS) -> np.ndarray:
    """Beat-to-beat intervals in seconds — the input to every HRV measure."""
    peaks = np.asarray(peaks)
    if peaks.size < 2:
        raise ValueError("need at least two peaks to measure intervals")
    return np.diff(peaks) / fs


def signal_to_noise(clean: np.ndarray, noisy: np.ndarray) -> float:
    """SNR in decibels, given the clean signal and its corrupted version.

    Only computable because the clean signal exists — which is the whole
    argument for synthesising it. On real data this number is unavailable
    and every filtering claim becomes a matter of opinion.
    """
    clean = np.asarray(clean, dtype=float)
    noisy = np.asarray(noisy, dtype=float)
    if clean.shape != noisy.shape:
        raise ValueError(f"shapes differ: {clean.shape} and {noisy.shape}")
    noise = noisy - clean
    noise_power = float(np.mean(noise ** 2))
    if noise_power == 0:
        return float("inf")
    return float(10.0 * np.log10(np.mean(clean ** 2) / noise_power))


# --- Day 2 -----------------------------------------------------------------


def baseline_wander(signal: np.ndarray, fs: float = DEFAULT_FS,
                    amplitude: float = 0.3, frequency: float = 0.25,
                    seed: int | None = None) -> np.ndarray:
    """Slow drift of the whole trace, mostly from breathing.

    A respiration cycle is 12-20 breaths a minute, so 0.2-0.33 Hz, and
    the chest movement drags the electrode baseline with it. The result
    is the trace wandering up and down the screen while the beats
    themselves are untouched.

    That last part matters for everything downstream: wander moves the
    signal, not the **timing**. A detector that finds peaks by position
    is unaffected; one that compares against a fixed amplitude threshold
    fails completely, and Day 3 measures exactly that difference.

    >>> signal, _ = synthesise_ecg(duration=2.0, fs=100.0)
    >>> noisy = baseline_wander(signal, fs=100.0)
    >>> len(noisy) == len(signal)
    True
    """
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    if frequency <= 0:
        raise ValueError(f"frequency must be positive, got {frequency}")
    time = np.arange(len(signal)) / fs
    phase = 0.0 if seed is None else np.random.default_rng(seed).uniform(0, 2 * np.pi)
    return signal + amplitude * np.sin(2 * np.pi * frequency * time + phase)


def mains_hum(signal: np.ndarray, fs: float = DEFAULT_FS,
              amplitude: float = 0.05, frequency: float = 50.0) -> np.ndarray:
    """Powerline interference: a pure tone at 50 Hz, or 60 Hz in the Americas.

    The frequency is not a detail. A QRS complex has most of its energy
    between 5 and 20 Hz with a tail out past 40, so a 50 Hz notch is
    close to the signal and a 60 Hz notch is a little further away. Day 3
    measures what removing it costs the QRS.

    It is also perfectly periodic, which makes it the one artefact here
    that a filter can remove almost exactly - and the demo shows why that
    is not true of the other two.
    """
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    if frequency <= 0:
        raise ValueError(f"frequency must be positive, got {frequency}")
    if frequency >= fs / 2:
        raise ValueError(
            f"{frequency} Hz is at or above the Nyquist limit for fs={fs}; "
            "it would alias to a lower frequency rather than appear where it is")
    time = np.arange(len(signal)) / fs
    return signal + amplitude * np.sin(2 * np.pi * frequency * time)


def motion_artefact(signal: np.ndarray, fs: float = DEFAULT_FS,
                    bursts: int = 3, amplitude: float = 1.5,
                    width: float = 0.4, seed: int = 0) -> np.ndarray:
    """Short, large excursions from the electrode moving on the skin.

    The hardest of the three to FILTER, and the reason is its shape
    rather than its size: a burst is broad-band and transient, so it
    overlaps the QRS in both frequency and time. There is no band to
    remove that does not also contain the beat, which is Day 3's problem.

    "Hardest to filter" is not the same as "most damaging", and the demo
    measures the difference. At equal signal-to-noise ratio a burst does
    LESS damage to a threshold detector than continuous noise does,
    because it is confined to a few hundred milliseconds while mains hum
    is present at every sample. I had this the wrong way round until the
    equal-SNR table was run.

    Each burst here is a Gaussian envelope over noise, which is a
    caricature of what an electrode does when a patient shifts - and
    enough to produce excursions taller than the R peak, which is the
    property Day 4's detector has to survive.
    """
    if bursts < 0:
        raise ValueError(f"bursts must be non-negative, got {bursts}")
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    rng = np.random.default_rng(seed)
    noisy = signal.astype(float).copy()
    time = np.arange(len(signal)) / fs
    duration = len(signal) / fs
    for _ in range(bursts):
        centre = rng.uniform(0.1 * duration, 0.9 * duration)
        envelope = np.exp(-0.5 * ((time - centre) / width) ** 2)
        noisy += amplitude * envelope * rng.normal(0.0, 1.0, size=len(signal))
    return noisy


def sensor_noise(signal: np.ndarray, amplitude: float = 0.02,
                 seed: int = 0) -> np.ndarray:
    """Broadband white noise from the amplifier and the electrode contact."""
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    rng = np.random.default_rng(seed)
    return signal + rng.normal(0.0, amplitude, size=len(signal))


def dominant_frequency(signal: np.ndarray, fs: float = DEFAULT_FS,
                       ignore_dc: bool = True) -> float:
    """The frequency carrying the most energy, by FFT.

    Used to show that each artefact sits somewhere different in the
    spectrum - which is what makes two of them filterable and one not.
    """
    spectrum = np.abs(np.fft.rfft(signal))
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    if ignore_dc and len(spectrum) > 1:
        spectrum = spectrum[1:]
        frequencies = frequencies[1:]
    return float(frequencies[int(np.argmax(spectrum))])


def band_energy(signal: np.ndarray, low: float, high: float,
                fs: float = DEFAULT_FS) -> float:
    """Fraction of the signal's energy between ``low`` and ``high`` Hz."""
    if low < 0 or high <= low:
        raise ValueError(f"expected 0 <= low < high, got {low} and {high}")
    spectrum = np.abs(np.fft.rfft(signal)) ** 2
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    total = spectrum.sum()
    if total <= 0:
        return 0.0
    selected = (frequencies >= low) & (frequencies < high)
    return float(spectrum[selected].sum() / total)


def threshold_detect(signal: np.ndarray, threshold: float = 0.5,
                     fs: float = DEFAULT_FS, refractory: float = 0.2) -> np.ndarray:
    """The most naive R-peak detector there is: sample above a fixed level.

    Deliberately bad, and deliberately the obvious first idea. It is here
    so that Day 2 can show which noise breaks it and Day 3 can show what
    filtering repairs — a detector nobody would ship, used as an
    instrument.

    ``refractory`` suppresses repeat detections within 200 ms, because
    the heart physically cannot beat twice that fast and without it every
    R peak counts as a dozen.
    """
    if refractory < 0:
        raise ValueError(f"refractory must be non-negative, got {refractory}")
    above = np.where(signal > threshold)[0]
    if not len(above):
        return np.array([], dtype=int)
    gap = int(round(refractory * fs))
    peaks = [above[0]]
    for index in above[1:]:
        if index - peaks[-1] >= gap:
            peaks.append(index)
    # Within each detected region, take the actual maximum.
    refined = []
    for start in peaks:
        end = min(start + gap, len(signal))
        refined.append(start + int(np.argmax(signal[start:end])))
    return np.array(sorted(set(refined)), dtype=int)


def match_peaks(detected: np.ndarray, truth: np.ndarray,
                tolerance_samples: int = 25) -> dict:
    """Score detections against the ground truth Day 1 wrote down.

    A detection counts if it lands within ``tolerance_samples`` of a true
    peak - 100 ms at 250 Hz, which is about the width of a QRS. Each true
    peak can be matched once, so a detector cannot score twice for
    finding the same beat twice.
    """
    truth = list(truth)
    unmatched = set(range(len(truth)))
    true_positive = 0
    for position in detected:
        best = None
        for index in unmatched:
            if abs(truth[index] - position) <= tolerance_samples:
                if best is None or abs(truth[index] - position) < abs(truth[best] - position):
                    best = index
        if best is not None:
            unmatched.discard(best)
            true_positive += 1
    false_positive = len(detected) - true_positive
    false_negative = len(unmatched)
    sensitivity = true_positive / len(truth) if len(truth) else 0.0
    precision = (true_positive / len(detected)) if len(detected) else 0.0
    return {"true_positive": true_positive, "false_positive": false_positive,
            "false_negative": false_negative, "sensitivity": sensitivity,
            "precision": precision}


def amplitude_for_snr(clean: np.ndarray, make_noisy, target_db: float,
                      low: float = 1e-4, high: float = 20.0,
                      steps: int = 60) -> float:
    """The artefact amplitude that produces a chosen signal-to-noise ratio.

    Bisection, because SNR falls monotonically with amplitude for every
    artefact here. It exists so the demo can compare artefacts at *equal*
    SNR rather than at equal amplitude, which is the only comparison that
    says anything about the artefact rather than about the units.
    """
    for _ in range(steps):
        middle = (low + high) / 2
        if signal_to_noise(clean, make_noisy(middle)) > target_db:
            low = middle
        else:
            high = middle
    return (low + high) / 2


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every signal here is generated by this file.")
    print()

    clean, truth = synthesise_ecg(duration=20.0, hrv=0.03, seed=0)
    print(f"20 s at {DEFAULT_FS:.0f} Hz, {len(truth)} beats placed, "
          f"ground truth known exactly")

    print()
    print("=" * 72)
    print("1. four artefacts, and where each one lives")
    print("=" * 72)
    variants = {
        "clean": clean,
        "baseline wander": baseline_wander(clean),
        "mains hum 50 Hz": mains_hum(clean),
        "sensor noise": sensor_noise(clean),
        "motion artefact": motion_artefact(clean),
    }
    print(f"  {'signal':<18}{'SNR dB':>9}{'dominant Hz':>13}"
          f"{'energy 5-20 Hz':>16}{'energy >40 Hz':>15}")
    for name, signal in variants.items():
        snr = signal_to_noise(clean, signal)
        shown = "  inf" if snr == float("inf") else f"{snr:5.1f}"
        print(f"  {name:<18}{shown:>9}{dominant_frequency(signal):>13.2f}"
              f"{band_energy(signal, 5, 20):>16.0%}"
              f"{band_energy(signal, 40, DEFAULT_FS / 2):>15.0%}")
    print()
    print("  wander pulls the dominant frequency down to its own 0.25 Hz and")
    print("  halves the share of energy in the QRS band. Hum and sensor noise")
    print("  leave the low band alone. That separation is what Day 3's")
    print("  filters exploit, and motion artefact is the one that resists")
    print("  because it is spread across the whole spectrum.")

    print()
    print("=" * 72)
    print("2. what each costs a naive detector")
    print("=" * 72)
    print("  threshold_detect is the obvious first idea: any sample above")
    print("  0.5 mV, with a 200 ms refractory period. Nobody would ship it.")
    print()
    print(f"  {'signal':<18}{'sensitivity':>13}{'precision':>11}"
          f"{'found':>7}{'true':>6}")
    for name, signal in variants.items():
        detected = threshold_detect(signal)
        scores = match_peaks(detected, truth)
        print(f"  {name:<18}{scores['sensitivity']:>13.0%}"
              f"{scores['precision']:>11.0%}{len(detected):>7}{len(truth):>6}")
    print()
    print("  sensitivity never moves. The detector does not MISS beats under")
    print("  any of these - noise adds energy, so the true peaks stay above")
    print("  the line. Every failure here is a false positive, and reporting")
    print("  'the detector is 100% sensitive' would be true and useless.")

    print()
    print("=" * 72)
    print("3. the measurement that matters: equal SNR, unequal damage")
    print("=" * 72)
    print("  comparing artefacts at equal amplitude compares units. So")
    print("  tune each one until the signal-to-noise ratio is identical:")
    makers = {
        "baseline wander": lambda a: baseline_wander(clean, amplitude=a),
        "mains hum": lambda a: mains_hum(clean, amplitude=a),
        "sensor noise": lambda a: sensor_noise(clean, amplitude=a),
        "motion artefact": lambda a: motion_artefact(clean, amplitude=a),
    }
    for target in (10.0, 0.0, -5.0):
        print()
        print(f"  SNR = {target:+.0f} dB")
        print(f"    {'artefact':<18}{'amplitude':>11}{'sensitivity':>13}"
              f"{'precision':>11}{'found':>7}")
        for name, make in makers.items():
            amplitude = amplitude_for_snr(clean, make, target)
            detected = threshold_detect(make(amplitude))
            scores = match_peaks(detected, truth)
            print(f"    {name:<18}{amplitude:>11.3f}{scores['sensitivity']:>13.0%}"
                  f"{scores['precision']:>11.0%}{len(detected):>7}")
    print()
    print("  at 0 dB - by construction the same amount of noise power -")
    print("  precision runs from 50% to 80% depending only on WHICH")
    print("  artefact. At -5 dB it runs from 28% to 65%. SNR is out by more")
    print("  than a factor of two as a predictor of damage.")
    print()
    print("  and the ordering is not the intuitive one. Mains hum and sensor")
    print("  noise - the two a filter removes most easily - do MORE damage")
    print("  than motion artefact, which no filter can touch. A burst is")
    print("  confined to a few hundred milliseconds; hum is present at every")
    print("  sample, so it lifts the whole trace across the threshold over")
    print("  and over.")
    print()
    print("  I had this backwards before the table was run, and the")
    print("  motion_artefact docstring says so. 'Hardest to filter' and")
    print("  'most damaging' are different questions with different answers.")

    print()
    print("=" * 72)
    print("4. wander moves the signal, not the timing")
    print("=" * 72)
    wandering = baseline_wander(clean, amplitude=0.4)
    detected = threshold_detect(wandering)
    scores = match_peaks(detected, truth)
    print(f"  baseline wander at 0.4 mV: sensitivity {scores['sensitivity']:.0%}, "
          f"precision {scores['precision']:.0%}")
    print()
    print("  every true beat is still found, in the right place. What breaks")
    print("  is the fixed threshold, because the trace now drifts across it")
    print("  whether or not there is a beat.")
    print()
    print("  that distinction decides Day 3's design. A detector that")
    print("  compares a sample against a FIXED level is destroyed by wander;")
    print("  one that compares against the local baseline is not, and Day 3")
    print("  measures both against this exact signal.")
