"""Day 3 — Filtering: moving average, and what it does to the peaks.

Three filters against Day 2's three artefacts, and the recurring answer
is that the filter costs something the beat needed.

**Baseline removal** works, and its window is a real trade: 0.1 s keeps
only 82% of the R peak because the average starts tracking the QRS
itself, 2.0 s leaves a quarter of the wander behind. Anywhere between
0.4 and 1.0 s is fine, which is the useful part - the knob is not sharp.

**Smoothing** destroys what it protects. A QRS is 80 ms wide, so a
moving average approaching that width averages the peak against its
neighbours: 83% of the R peak survives a 20 ms window and 20% survives
100 ms. The beat *is* the high-frequency content.

**The causal delay is real and predictable** - a backward-looking mean of
w samples delays by (w-1)/2, which the measurements confirm at small
windows. At large ones they stop confirming it, because the peak has been
flattened away and the measurement is now reporting the distance to some
other local maximum. A measurement whose subject has been destroyed does
not return an error.

**The notch costs nothing here, and that is suspicious.** The synthetic
QRS holds 0.0006% of its energy where a 50 Hz notch cuts, because Day 1
built it from smooth Gaussians. A real QRS has a sharp upstroke and
content past 40 Hz. This is the first place Day 1's caricature changes an
answer, and it is flagged rather than enjoyed.

And the day's own conclusion undercuts it: **two of the three artefacts
are better answered by changing the detector than by filtering.** An
adaptive threshold takes precision under wander from 73% to 100% with no
filter, no window and no delay — within a range. Past 0.8 mV of wander
both detectors collapse and the adaptive one's *sensitivity* is the worse
of the two, because the local maximum it compares against is itself
inflated by the drift.

NOT A MEDICAL DEVICE. Every signal in this repo is generated by it.
"""

from __future__ import annotations

import numpy as np

# --- reused from day01 -----------------------------------------------------
# Byte-identical to 01_biosignals/day01_synthetic_ecg/ecg.py.



#: Typical adult resting heart rate, in beats per minute.
DEFAULT_BPM = 72.0

#: Sampling rate in Hz. 250 is a common clinical monitor rate and is
#: comfortably above the Nyquist limit for the ~40 Hz content of a QRS.
DEFAULT_FS = 250.0


def _gaussian(t: np.ndarray, centre: float, width: float, height: float) -> np.ndarray:
    """One smooth bump, used for each of the P, Q, R, S and T deflections."""
    return height * np.exp(-0.5 * ((t - centre) / width) ** 2)


def beat_waveform(fs: float = DEFAULT_FS, duration: float = 0.8) -> np.ndarray:
    """One cardiac cycle, as a sum of five Gaussians.

    The parameters below are shaped to look like lead II: a small upright
    P, a sharp tall R flanked by small negative Q and S, and a broad
    low T. Amplitudes are in millivolts.

    The R peak sits at ``0.25 * duration`` deliberately, leaving room for
    the P wave before it. Day 4's detector must not assume that position.

    >>> wave = beat_waveform(fs=250.0, duration=0.8)
    >>> len(wave)
    200
    """
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if duration <= 0:
        raise ValueError(f"duration must be positive, got {duration}")

    samples = int(round(fs * duration))
    t = np.linspace(0.0, duration, samples, endpoint=False)
    r_time = 0.25 * duration

    wave = np.zeros(samples)
    wave += _gaussian(t, r_time - 0.16, 0.025, 0.12)   # P wave
    wave += _gaussian(t, r_time - 0.02, 0.008, -0.16)  # Q
    wave += _gaussian(t, r_time, 0.010, 1.20)          # R
    wave += _gaussian(t, r_time + 0.02, 0.008, -0.28)  # S
    wave += _gaussian(t, r_time + 0.18, 0.045, 0.30)   # T wave
    return wave


def synthesise_ecg(
    duration: float = 10.0,
    bpm: float = DEFAULT_BPM,
    fs: float = DEFAULT_FS,
    hrv: float = 0.0,
    seed: int = 0,
) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(signal, r_peak_samples)``.

    ``hrv`` is the standard deviation of beat-to-beat interval jitter, in
    seconds. At 0 the rhythm is metronomic, which is unphysiological — a
    real heart never is — so Day 4 uses a non-zero value and Day 1 keeps
    both available to show the difference.

    The returned peak positions are **ground truth**, not an estimate.
    Everything downstream is scored against them.

    >>> signal, peaks = synthesise_ecg(duration=4.0, bpm=60.0, fs=100.0)
    >>> len(signal), len(peaks)
    (400, 4)
    """
    if duration <= 0:
        raise ValueError(f"duration must be positive, got {duration}")
    if bpm <= 0:
        raise ValueError(f"bpm must be positive, got {bpm}")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if hrv < 0:
        raise ValueError(f"hrv must be non-negative, got {hrv}")

    rng = np.random.default_rng(seed)
    total_samples = int(round(duration * fs))
    signal = np.zeros(total_samples)
    peaks: list[int] = []

    mean_interval = 60.0 / bpm
    beat = beat_waveform(fs=fs, duration=mean_interval)
    r_offset = int(round(0.25 * len(beat)))

    time = 0.0
    while True:
        start = int(round(time * fs))
        if start >= total_samples:
            break
        end = min(start + len(beat), total_samples)
        signal[start:end] += beat[: end - start]
        r_position = start + r_offset
        if r_position < total_samples:
            peaks.append(r_position)

        interval = mean_interval
        if hrv > 0:
            interval = max(0.25, mean_interval + rng.normal(0.0, hrv))
        time += interval

    return signal, np.array(peaks, dtype=int)


def heart_rate(peaks: np.ndarray, fs: float = DEFAULT_FS) -> float:
    """Mean heart rate in beats per minute, from R-peak positions.

    Computed from the **intervals**, not from ``len(peaks) / duration``.
    The two differ whenever the recording does not start and end exactly
    on a beat, and the interval form is what a monitor actually reports.

    >>> round(heart_rate(np.array([0, 250, 500, 750]), fs=250.0), 3)
    60.0
    """
    peaks = np.asarray(peaks)
    if peaks.size < 2:
        raise ValueError("need at least two peaks to measure a rate")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    intervals = np.diff(peaks) / fs
    return float(60.0 / intervals.mean())


def rr_intervals(peaks: np.ndarray, fs: float = DEFAULT_FS) -> np.ndarray:
    """Beat-to-beat intervals in seconds — the input to every HRV measure."""
    peaks = np.asarray(peaks)
    if peaks.size < 2:
        raise ValueError("need at least two peaks to measure intervals")
    return np.diff(peaks) / fs


def signal_to_noise(clean: np.ndarray, noisy: np.ndarray) -> float:
    """SNR in decibels, given the clean signal and its corrupted version.

    Only computable because the clean signal exists — which is the whole
    argument for synthesising it. On real data this number is unavailable
    and every filtering claim becomes a matter of opinion.
    """
    clean = np.asarray(clean, dtype=float)
    noisy = np.asarray(noisy, dtype=float)
    if clean.shape != noisy.shape:
        raise ValueError(f"shapes differ: {clean.shape} and {noisy.shape}")
    noise = noisy - clean
    noise_power = float(np.mean(noise ** 2))
    if noise_power == 0:
        return float("inf")
    return float(10.0 * np.log10(np.mean(clean ** 2) / noise_power))


# --- Day 2 -----------------------------------------------------------------


def baseline_wander(signal: np.ndarray, fs: float = DEFAULT_FS,
                    amplitude: float = 0.3, frequency: float = 0.25,
                    seed: int | None = None) -> np.ndarray:
    """Slow drift of the whole trace, mostly from breathing.

    A respiration cycle is 12-20 breaths a minute, so 0.2-0.33 Hz, and
    the chest movement drags the electrode baseline with it. The result
    is the trace wandering up and down the screen while the beats
    themselves are untouched.

    That last part matters for everything downstream: wander moves the
    signal, not the **timing**. A detector that finds peaks by position
    is unaffected; one that compares against a fixed amplitude threshold
    fails completely, and Day 3 measures exactly that difference.

    >>> signal, _ = synthesise_ecg(duration=2.0, fs=100.0)
    >>> noisy = baseline_wander(signal, fs=100.0)
    >>> len(noisy) == len(signal)
    True
    """
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    if frequency <= 0:
        raise ValueError(f"frequency must be positive, got {frequency}")
    time = np.arange(len(signal)) / fs
    phase = 0.0 if seed is None else np.random.default_rng(seed).uniform(0, 2 * np.pi)
    return signal + amplitude * np.sin(2 * np.pi * frequency * time + phase)


def mains_hum(signal: np.ndarray, fs: float = DEFAULT_FS,
              amplitude: float = 0.05, frequency: float = 50.0) -> np.ndarray:
    """Powerline interference: a pure tone at 50 Hz, or 60 Hz in the Americas.

    The frequency is not a detail. A QRS complex has most of its energy
    between 5 and 20 Hz with a tail out past 40, so a 50 Hz notch is
    close to the signal and a 60 Hz notch is a little further away. Day 3
    measures what removing it costs the QRS.

    It is also perfectly periodic, which makes it the one artefact here
    that a filter can remove almost exactly - and the demo shows why that
    is not true of the other two.
    """
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    if frequency <= 0:
        raise ValueError(f"frequency must be positive, got {frequency}")
    if frequency >= fs / 2:
        raise ValueError(
            f"{frequency} Hz is at or above the Nyquist limit for fs={fs}; "
            "it would alias to a lower frequency rather than appear where it is")
    time = np.arange(len(signal)) / fs
    return signal + amplitude * np.sin(2 * np.pi * frequency * time)


def motion_artefact(signal: np.ndarray, fs: float = DEFAULT_FS,
                    bursts: int = 3, amplitude: float = 1.5,
                    width: float = 0.4, seed: int = 0) -> np.ndarray:
    """Short, large excursions from the electrode moving on the skin.

    The hardest of the three to FILTER, and the reason is its shape
    rather than its size: a burst is broad-band and transient, so it
    overlaps the QRS in both frequency and time. There is no band to
    remove that does not also contain the beat, which is Day 3's problem.

    "Hardest to filter" is not the same as "most damaging", and the demo
    measures the difference. At equal signal-to-noise ratio a burst does
    LESS damage to a threshold detector than continuous noise does,
    because it is confined to a few hundred milliseconds while mains hum
    is present at every sample. I had this the wrong way round until the
    equal-SNR table was run.

    Each burst here is a Gaussian envelope over noise, which is a
    caricature of what an electrode does when a patient shifts - and
    enough to produce excursions taller than the R peak, which is the
    property Day 4's detector has to survive.
    """
    if bursts < 0:
        raise ValueError(f"bursts must be non-negative, got {bursts}")
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    rng = np.random.default_rng(seed)
    noisy = signal.astype(float).copy()
    time = np.arange(len(signal)) / fs
    duration = len(signal) / fs
    for _ in range(bursts):
        centre = rng.uniform(0.1 * duration, 0.9 * duration)
        envelope = np.exp(-0.5 * ((time - centre) / width) ** 2)
        noisy += amplitude * envelope * rng.normal(0.0, 1.0, size=len(signal))
    return noisy


def sensor_noise(signal: np.ndarray, amplitude: float = 0.02,
                 seed: int = 0) -> np.ndarray:
    """Broadband white noise from the amplifier and the electrode contact."""
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    rng = np.random.default_rng(seed)
    return signal + rng.normal(0.0, amplitude, size=len(signal))


def dominant_frequency(signal: np.ndarray, fs: float = DEFAULT_FS,
                       ignore_dc: bool = True) -> float:
    """The frequency carrying the most energy, by FFT.

    Used to show that each artefact sits somewhere different in the
    spectrum - which is what makes two of them filterable and one not.
    """
    spectrum = np.abs(np.fft.rfft(signal))
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    if ignore_dc and len(spectrum) > 1:
        spectrum = spectrum[1:]
        frequencies = frequencies[1:]
    return float(frequencies[int(np.argmax(spectrum))])


def band_energy(signal: np.ndarray, low: float, high: float,
                fs: float = DEFAULT_FS) -> float:
    """Fraction of the signal's energy between ``low`` and ``high`` Hz."""
    if low < 0 or high <= low:
        raise ValueError(f"expected 0 <= low < high, got {low} and {high}")
    spectrum = np.abs(np.fft.rfft(signal)) ** 2
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    total = spectrum.sum()
    if total <= 0:
        return 0.0
    selected = (frequencies >= low) & (frequencies < high)
    return float(spectrum[selected].sum() / total)


def threshold_detect(signal: np.ndarray, threshold: float = 0.5,
                     fs: float = DEFAULT_FS, refractory: float = 0.2) -> np.ndarray:
    """The most naive R-peak detector there is: sample above a fixed level.

    Deliberately bad, and deliberately the obvious first idea. It is here
    so that Day 2 can show which noise breaks it and Day 3 can show what
    filtering repairs — a detector nobody would ship, used as an
    instrument.

    ``refractory`` suppresses repeat detections within 200 ms, because
    the heart physically cannot beat twice that fast and without it every
    R peak counts as a dozen.
    """
    if refractory < 0:
        raise ValueError(f"refractory must be non-negative, got {refractory}")
    above = np.where(signal > threshold)[0]
    if not len(above):
        return np.array([], dtype=int)
    gap = int(round(refractory * fs))
    peaks = [above[0]]
    for index in above[1:]:
        if index - peaks[-1] >= gap:
            peaks.append(index)
    # Within each detected region, take the actual maximum.
    refined = []
    for start in peaks:
        end = min(start + gap, len(signal))
        refined.append(start + int(np.argmax(signal[start:end])))
    return np.array(sorted(set(refined)), dtype=int)


def match_peaks(detected: np.ndarray, truth: np.ndarray,
                tolerance_samples: int = 25) -> dict:
    """Score detections against the ground truth Day 1 wrote down.

    A detection counts if it lands within ``tolerance_samples`` of a true
    peak - 100 ms at 250 Hz, which is about the width of a QRS. Each true
    peak can be matched once, so a detector cannot score twice for
    finding the same beat twice.
    """
    truth = list(truth)
    unmatched = set(range(len(truth)))
    true_positive = 0
    for position in detected:
        best = None
        for index in unmatched:
            if abs(truth[index] - position) <= tolerance_samples:
                if best is None or abs(truth[index] - position) < abs(truth[best] - position):
                    best = index
        if best is not None:
            unmatched.discard(best)
            true_positive += 1
    false_positive = len(detected) - true_positive
    false_negative = len(unmatched)
    sensitivity = true_positive / len(truth) if len(truth) else 0.0
    precision = (true_positive / len(detected)) if len(detected) else 0.0
    return {"true_positive": true_positive, "false_positive": false_positive,
            "false_negative": false_negative, "sensitivity": sensitivity,
            "precision": precision}


def amplitude_for_snr(clean: np.ndarray, make_noisy, target_db: float,
                      low: float = 1e-4, high: float = 20.0,
                      steps: int = 60) -> float:
    """The artefact amplitude that produces a chosen signal-to-noise ratio.

    Bisection, because SNR falls monotonically with amplitude for every
    artefact here. It exists so the demo can compare artefacts at *equal*
    SNR rather than at equal amplitude, which is the only comparison that
    says anything about the artefact rather than about the units.
    """
    for _ in range(steps):
        middle = (low + high) / 2
        if signal_to_noise(clean, make_noisy(middle)) > target_db:
            low = middle
        else:
            high = middle
    return (low + high) / 2


# --- Day 3 -----------------------------------------------------------------


def moving_average(signal: np.ndarray, window: int, causal: bool = False) -> np.ndarray:
    """The simplest low-pass filter there is: the mean of a sliding window.

    ``causal`` decides whether the window looks backwards only (as it
    must in real time, on a monitor, where the future has not happened
    yet) or is centred on the sample (as it may offline, on a recording).

    That flag is the whole of section 2 below. A causal window of ``w``
    samples delays everything by ``(w-1)/2`` samples, which for a 0.6 s
    window at 250 Hz is 300 ms — longer than a QRS complex, and applied
    to a measurement whose entire purpose is timing.

    >>> moving_average(np.array([0.0, 3.0, 0.0]), window=3).round(3)
    array([1.   , 1.   , 1.   ])
    """
    if window < 1:
        raise ValueError(f"window must be at least 1 sample, got {window}")
    if window == 1:
        return signal.astype(float).copy()
    kernel = np.ones(window) / window
    padded = np.pad(signal.astype(float), (window - 1, window - 1), mode="edge")
    smoothed = np.convolve(padded, kernel, mode="valid")
    if causal:
        return smoothed[:len(signal)]
    offset = (window - 1) // 2
    return smoothed[offset:offset + len(signal)]


def remove_baseline(signal: np.ndarray, fs: float = DEFAULT_FS,
                    window_seconds: float = 0.6,
                    causal: bool = False) -> np.ndarray:
    """High-pass by subtraction: signal minus its own slow average.

    A moving average over a window longer than a beat estimates the
    baseline; subtracting it removes the drift. The window length is the
    only knob and it is a genuine trade, measured in the demo: too short
    and the average starts tracking the QRS itself, which subtracts the
    beat away; too long and slower wander survives.
    """
    window = max(1, int(round(window_seconds * fs)))
    return signal - moving_average(signal, window, causal=causal)


def notch_filter(signal: np.ndarray, fs: float = DEFAULT_FS,
                 frequency: float = 50.0, width: float = 2.0) -> np.ndarray:
    """Zero out one narrow band in the spectrum, then transform back.

    Not how a real monitor does it - a biquad IIR notch is cheaper and
    causal - but it isolates the question this day asks: a notch removes
    everything in its band, including whatever the SIGNAL had there, and
    the demo prices that.
    """
    if width <= 0:
        raise ValueError(f"width must be positive, got {width}")
    if frequency <= 0 or frequency >= fs / 2:
        raise ValueError(f"frequency must be between 0 and {fs / 2}, got {frequency}")
    spectrum = np.fft.rfft(signal)
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    spectrum[np.abs(frequencies - frequency) <= width / 2] = 0.0
    return np.fft.irfft(spectrum, n=len(signal))


def peak_amplitude(signal: np.ndarray, peaks: np.ndarray,
                   half_width: int = 10) -> float:
    """Mean height of the signal at the known R-peak positions.

    Measured at the ground-truth positions rather than at detected ones,
    so it reports what the filter did to the beat rather than what it did
    to the detector.
    """
    if not len(peaks):
        return 0.0
    heights = []
    for position in peaks:
        low = max(0, position - half_width)
        high = min(len(signal), position + half_width + 1)
        heights.append(signal[low:high].max())
    return float(np.mean(heights))


def peak_shift(signal: np.ndarray, peaks: np.ndarray,
               search: int = 60) -> float:
    """Mean samples between each true peak and the nearest local maximum.

    A causal filter delays the whole signal, so the beat arrives late.
    This measures by how much, which for a timing measurement is the
    number that matters more than amplitude.
    """
    if not len(peaks):
        return 0.0
    shifts = []
    for position in peaks:
        low = max(0, position - search)
        high = min(len(signal), position + search + 1)
        if high - low < 3:
            continue
        shifts.append(low + int(np.argmax(signal[low:high])) - position)
    return float(np.mean(shifts)) if shifts else 0.0


def adaptive_threshold_detect(signal: np.ndarray, fs: float = DEFAULT_FS,
                              window_seconds: float = 2.0,
                              factor: float = 0.5,
                              refractory: float = 0.2) -> np.ndarray:
    """Threshold against the LOCAL signal level rather than a fixed one.

    Day 2 showed that baseline wander destroys a fixed threshold while
    leaving the timing untouched. This is the repair: the threshold at
    each sample is ``factor`` of the local maximum, estimated over a
    window a few beats long, so drift moves the threshold with the
    signal.

    It is still not a good detector - Day 4 builds that - but it is the
    minimum change that survives the artefact Day 2 identified, and the
    demo measures whether it does.
    """
    if not 0 < factor < 1:
        raise ValueError(f"factor must be between 0 and 1, got {factor}")
    window = max(3, int(round(window_seconds * fs)))
    envelope = moving_average(np.abs(signal), window)
    local = envelope * 0
    half = window // 2
    for index in range(len(signal)):
        low = max(0, index - half)
        high = min(len(signal), index + half + 1)
        local[index] = signal[low:high].max()
    above = np.where(signal > factor * local)[0]
    if not len(above):
        return np.array([], dtype=int)
    gap = int(round(refractory * fs))
    starts = [above[0]]
    for index in above[1:]:
        if index - starts[-1] >= gap:
            starts.append(index)
    refined = []
    for start in starts:
        end = min(start + gap, len(signal))
        refined.append(start + int(np.argmax(signal[start:end])))
    return np.array(sorted(set(refined)), dtype=int)


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every signal here is generated by this file.")
    print()

    clean, truth = synthesise_ecg(duration=20.0, hrv=0.03, seed=0)
    baseline_amplitude = peak_amplitude(clean, truth)
    wandering = baseline_wander(clean, amplitude=0.4)

    print("=" * 72)
    print("1. removing baseline wander: the window is the whole design")
    print("=" * 72)
    print("  subtract a moving average longer than a beat. Too short and the")
    print("  average tracks the QRS and subtracts the beat away; too long and")
    print("  the wander survives.")
    print()
    print(f"  {'window s':>9}{'R amp kept':>12}{'wander left':>13}"
          f"{'sens':>7}{'prec':>7}")
    for seconds in (0.1, 0.2, 0.4, 0.6, 1.0, 2.0):
        filtered = remove_baseline(wandering, window_seconds=seconds)
        scores = match_peaks(threshold_detect(filtered), truth)
        print(f"  {seconds:>9.1f}"
              f"{peak_amplitude(filtered, truth) / baseline_amplitude:>12.0%}"
              f"{band_energy(filtered, 0, 1):>13.1%}"
              f"{scores['sensitivity']:>7.0%}{scores['precision']:>7.0%}")
    print()
    print("  both ends of the trade are visible: 0.1 s keeps only 82% of the")
    print("  R peak, 2.0 s leaves a quarter of the wander behind. Anywhere in")
    print("  the middle works, which is the useful finding - the knob is not")
    print("  sharp, and 0.4 to 1.0 s is all fine.")

    print()
    print("=" * 72)
    print("2. causal or centred: the delay a monitor cannot avoid")
    print("=" * 72)
    print("  a centred window uses samples from the future. On a recording")
    print("  that is free; on a monitor the future has not happened yet, so")
    print("  the window can only look back - and a backward-looking mean of")
    print("  w samples delays everything by (w-1)/2.")
    print()
    print(f"  {'window':>7}{'samples':>9}{'centred':>10}{'causal':>9}"
          f"{'causal ms':>11}{'predicted':>11}")
    for seconds in (0.02, 0.05, 0.1, 0.2):
        window = int(round(seconds * DEFAULT_FS))
        centred = moving_average(clean, window, causal=False)
        causal = moving_average(clean, window, causal=True)
        print(f"  {seconds:>7.2f}{window:>9}{peak_shift(centred, truth):>10.1f}"
              f"{peak_shift(causal, truth):>9.1f}"
              f"{peak_shift(causal, truth) / DEFAULT_FS * 1000:>11.0f}"
              f"{(window - 1) / 2:>11.1f}")
    print()
    print("  the first two rows match the prediction. The last two do not,")
    print("  and the reason is in the next table rather than in the filter:")
    print("  by 0.1 s the moving average has flattened the R peak to a fifth")
    print("  of its height, so peak_shift is finding some other local")
    print("  maximum and reporting the distance to that. Once a measurement's")
    print("  subject has been destroyed, the measurement stops meaning")
    print("  anything - it does not start returning an error.")

    print()
    print("=" * 72)
    print("3. what smoothing costs the thing it was protecting")
    print("=" * 72)
    print(f"  {'window':>7}{'R amp kept':>12}")
    for seconds in (0.02, 0.05, 0.1, 0.2):
        window = int(round(seconds * DEFAULT_FS))
        print(f"  {seconds:>7.2f}"
              f"{peak_amplitude(moving_average(clean, window), truth) / baseline_amplitude:>12.0%}")
    print()
    print("  a QRS complex is about 80 ms wide. A moving average approaching")
    print("  that width averages the peak against its own neighbours, and")
    print("  there is no setting that removes high-frequency noise without")
    print("  touching it - the beat IS the high-frequency content.")

    print()
    print("=" * 72)
    print("4. the notch that costs nothing, and why that is suspicious")
    print("=" * 72)
    hummy = mains_hum(clean, amplitude=0.3)
    print(f"  {'':<24}{'energy 48-52':>14}{'R amp kept':>12}{'SNR dB':>9}")
    print(f"  {'unfiltered':<24}{band_energy(hummy, 48, 52):>14.1%}"
          f"{peak_amplitude(hummy, truth) / baseline_amplitude:>12.0%}"
          f"{signal_to_noise(clean, hummy):>9.1f}")
    for width in (1.0, 5.0, 20.0):
        filtered = notch_filter(hummy, frequency=50.0, width=width)
        print(f"  {f'notch {width:.0f} Hz wide':<24}{band_energy(filtered, 48, 52):>14.1%}"
              f"{peak_amplitude(filtered, truth) / baseline_amplitude:>12.0%}"
              f"{signal_to_noise(clean, filtered):>9.1f}")
    print()
    print("  the hum goes entirely, the R peak is untouched, and even a")
    print("  20 Hz-wide notch costs nothing. That is too good, and the")
    print("  reason is a limitation of this repo rather than a fact about")
    print("  notch filters:")
    print()
    print(f"  {'band':>12}{'share of the clean signal':>28}")
    for low, high in ((0, 5), (5, 20), (20, 40), (40, 60), (48, 52)):
        print(f"  {f'{low}-{high} Hz':>12}{band_energy(clean, low, high):>28.4%}")
    print()
    print("  the synthetic QRS holds 0.0006% of its energy where the notch")
    print("  cuts, because Day 1 built it out of smooth Gaussians. A real")
    print("  QRS has a sharp upstroke and meaningful content past 40 Hz, so a")
    print("  50 Hz notch on real data does take something from the beat.")
    print("  Day 1 said the waveform is a caricature; this is the first place")
    print("  the caricature changes an answer.")

    print()
    print("=" * 72)
    print("5. motion artefact, where filtering runs out")
    print("=" * 72)
    motion = motion_artefact(clean, amplitude=1.5, seed=0)
    print(f"  {'treatment':<24}{'sens':>7}{'prec':>7}{'R amp':>8}")
    treatments = [
        ("none", motion),
        ("remove baseline 0.6 s", remove_baseline(motion, window_seconds=0.6)),
        ("notch 50 Hz", notch_filter(motion, frequency=50.0, width=5.0)),
        ("smooth 20 ms", moving_average(motion, 5)),
        ("smooth 50 ms", moving_average(motion, 12)),
    ]
    for name, signal in treatments:
        scores = match_peaks(threshold_detect(signal), truth)
        print(f"  {name:<24}{scores['sensitivity']:>7.0%}{scores['precision']:>7.0%}"
              f"{peak_amplitude(signal, truth) / baseline_amplitude:>8.0%}")
    print()
    print("  the two filters that fixed the other artefacts do nothing here,")
    print("  because a burst has energy in every band. Mild smoothing buys")
    print("  sixteen points of precision; twice as much smoothing takes")
    print("  sensitivity from 100% to 25%.")
    print()
    print("  that is the honest answer for motion artefact: there is no")
    print("  filter for it, only a narrow band of mild smoothing that helps")
    print("  a little before it starts deleting beats.")

    print()
    print("=" * 72)
    print("6. and the fix for wander was not a filter at all")
    print("=" * 72)
    print(f"  {'signal':<16}{'fixed threshold':>26}{'adaptive threshold':>26}")
    for name, signal in (("clean", clean), ("wander 0.4 mV", wandering)):
        fixed = match_peaks(threshold_detect(signal), truth)
        adaptive = match_peaks(adaptive_threshold_detect(signal), truth)
        print(f"  {name:<16}"
              f"{f'''sens {fixed['sensitivity']:.0%}  prec {fixed['precision']:.0%}''':>26}"
              f"{f'''sens {adaptive['sensitivity']:.0%}  prec {adaptive['precision']:.0%}''':>26}")
    print()
    print("  no filtering, no window to tune, no delay. Comparing each sample")
    print("  against the LOCAL signal level instead of a fixed one takes")
    print("  precision from 73% back to 100%, because Day 2 established that")
    print("  wander moves the signal and not the timing.")
    print()
    print("  but only within a range, and the range is worth knowing:")
    print()
    print(f"  {'wander mV':>10}{'fixed sens':>12}{'fixed prec':>12}"
          f"{'adapt sens':>12}{'adapt prec':>12}")
    for amplitude in (0.0, 0.2, 0.4, 0.6, 0.8, 1.2):
        drifting = baseline_wander(clean, amplitude=amplitude)
        fixed = match_peaks(threshold_detect(drifting), truth)
        adaptive = match_peaks(adaptive_threshold_detect(drifting), truth)
        print(f"  {amplitude:>10.1f}{fixed['sensitivity']:>12.0%}"
              f"{fixed['precision']:>12.0%}{adaptive['sensitivity']:>12.0%}"
              f"{adaptive['precision']:>12.0%}")
    print()
    print("  up to 0.4 mV the adaptive threshold is perfect where the fixed")
    print("  one has fallen to 73%. Past 0.8 mV both collapse - and the")
    print("  adaptive one's SENSITIVITY is now the worse of the two, because")
    print("  the local maximum it compares against is itself inflated by the")
    print("  wander. It is not a strictly better detector, it is a better")
    print("  detector over the range where wander is a nuisance rather than")
    print("  the dominant signal.")
    print()
    print("  the filter chapter's own conclusion, then: two of the three")
    print("  artefacts here are better answered by changing the detector than")
    print("  by cleaning the signal - inside a range that has to be stated.")
    print("  Day 4 builds the detector properly.")
