"""Day 8 — Calibration: a 30% risk that is right 30% of the time.

Day 6 found that AUC does not move with prevalence. This day finds the
harder half of the same fact: **AUC does not move with calibration
either**.

Distort the predicted probabilities with any strictly monotone transform
and the ranking is untouched by construction. Over four such distortions
the AUC reads 0.7353 every time, to four decimal places, while the
expected calibration error moves by a factor of a hundred. A paper
reporting AUC 0.74 has said nothing whatsoever about whether its 30%
means 30%.

The Brier score sees what AUC cannot, and its decomposition says why:

    Brier = reliability - resolution + uncertainty

The distortion moved the reliability term seventy-fold and left
resolution and uncertainty exactly where they were. Resolution is
discrimination — the thing AUC measures — and uncertainty belongs to the
base rate.

Platt scaling repairs it and, being monotone, cannot change the AUC.

The consequence is worse than a wrong number on a report. Day 7's
threshold arithmetic assumes the predicted probability is a probability;
run the same cost ratio on distorted scores and it selects a different
cut, a different sensitivity and a different clinic. **A miscalibrated
model silently invalidates every decision rule built on top of it.**

NOT A MEDICAL DEVICE. Every patient in this repo is generated by it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# --- Day 5 -----------------------------------------------------------------

#: The features of the synthetic cohort, and the coefficients that
#: generated it. Everything in Level 2 is scored against these numbers,
#: for the same reason Day 1 generated its own R peaks: a coefficient
#: estimated from real data can only be compared with somebody else's
#: estimate, and an estimate is not a truth.
TRUE_COEFFICIENTS = {
    "age_decades_over_50": 0.55,
    "systolic_over_120_per_10": 0.35,
    "cholesterol_over_5_per_1": 0.30,
    "smoker": 0.80,
    "diabetic": 0.90,
}

#: With the feature distribution below this gives an event rate near 26%.
#: ``make_cohort`` can solve for a different one - prevalence is the
#: subject of Day 6 and a parameter of Day 7, so it had better be a knob
#: rather than a constant chosen once and described inaccurately.
TRUE_INTERCEPT = -2.6

FEATURE_NAMES = tuple(TRUE_COEFFICIENTS)


@dataclass(frozen=True)
class Cohort:
    """A synthetic patient cohort with a known generating model.

    ``x`` holds the features in ``FEATURE_NAMES`` order, already centred
    on clinically meaningful reference points - age in decades past 50,
    systolic pressure in units of 10 mmHg past 120 - so that a
    coefficient reads as "per decade" rather than "per year" and the
    intercept is the log-odds of a reference patient rather than of a
    newborn with no blood pressure.
    """

    x: np.ndarray
    y: np.ndarray
    risk: np.ndarray
    names: tuple = FEATURE_NAMES

    def __len__(self) -> int:
        return len(self.y)

    @property
    def prevalence(self) -> float:
        return float(self.y.mean())


def sigmoid(z: np.ndarray) -> np.ndarray:
    """1 / (1 + exp(-z)), written so it does not overflow.

    ``exp(800)`` is infinity in float64, and a linear predictor of 800 is
    not unusual once a model is confident. The two-branch form keeps the
    exponent negative on both sides.

    It still **saturates**: this returns exactly 1.0 from z = 37 upward,
    because ``1 + 2.2e-16`` is 1.0 at double precision. Nothing is wrong
    with the arithmetic - the value has simply left the range float64 can
    distinguish from certainty - and it is why ``log_loss`` clips. A
    patient predicted at exactly 1.0 who has no event scores an infinite
    loss, and one of them would make the mean over four thousand patients
    infinite too.

    >>> sigmoid(np.array([0.0])).round(4)
    array([0.5])
    >>> np.isfinite(sigmoid(np.array([-800.0, 800.0]))).all()
    True
    """
    z = np.asarray(z, dtype=float)
    out = np.empty_like(z)
    positive = z >= 0
    out[positive] = 1.0 / (1.0 + np.exp(-z[positive]))
    exponential = np.exp(z[~positive])
    out[~positive] = exponential / (1.0 + exponential)
    return out


def intercept_for_prevalence(prevalence: float, n: int = 20000, seed: int = 0,
                             coefficients: dict | None = None,
                             correlate_cholesterol: float = 0.0) -> float:
    """The intercept that makes the mean true risk equal ``prevalence``.

    Bisection on a large draw. Exists because Day 6 sweeps prevalence and
    Day 7 tunes against it, and hard-coding one intercept and describing
    its consequence from memory is how a comment ends up claiming 12%
    where the data says 26%.
    """
    if not 0 < prevalence < 1:
        raise ValueError(f"prevalence must be in (0,1), got {prevalence}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    features = make_cohort(n=n, seed=seed, coefficients=coefficients,
                           correlate_cholesterol=correlate_cholesterol).x
    linear = features @ weights
    low, high = -20.0, 20.0
    for _ in range(80):
        middle = (low + high) / 2
        if sigmoid(middle + linear).mean() < prevalence:
            low = middle
        else:
            high = middle
    return (low + high) / 2


def make_cohort(n: int = 4000, seed: int = 0,
                coefficients: dict | None = None,
                intercept: float = TRUE_INTERCEPT,
                correlate_cholesterol: float = 0.0,
                prevalence: float | None = None) -> Cohort:
    """Draw patients, compute their true risk, and flip a coin each.

    The outcome is **sampled** from the true risk rather than thresholded
    at it. That distinction is the whole of Day 8: a patient with a 30%
    risk who does not have the event is not a model error, and a dataset
    built by thresholding would make calibration meaningless.

    ``correlate_cholesterol`` makes cholesterol partly a function of age,
    which is true of real cohorts and is what Day 5's last section is
    about.
    """
    if n < 1:
        raise ValueError(f"n must be positive, got {n}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    if prevalence is not None:
        intercept = intercept_for_prevalence(
            prevalence, coefficients=coefficients,
            correlate_cholesterol=correlate_cholesterol)
    rng = np.random.default_rng(seed)

    age_years = rng.normal(58.0, 9.0, size=n)
    age = (age_years - 50.0) / 10.0
    systolic = (rng.normal(132.0, 16.0, size=n) - 120.0) / 10.0
    base_cholesterol = rng.normal(5.4, 1.0, size=n)
    if correlate_cholesterol:
        base_cholesterol = (base_cholesterol
                            + correlate_cholesterol * age * 1.0)
    cholesterol = base_cholesterol - 5.0
    smoker = (rng.random(n) < 0.28).astype(float)
    diabetic = (rng.random(n) < 0.15).astype(float)

    x = np.column_stack([age, systolic, cholesterol, smoker, diabetic])
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    risk = sigmoid(intercept + x @ weights)
    y = (rng.random(n) < risk).astype(float)
    return Cohort(x=x, y=y, risk=risk)


def log_loss(y: np.ndarray, probability: np.ndarray, eps: float = 1e-12) -> float:
    """Mean negative log-likelihood, the thing the fit minimises.

    Clipped away from 0 and 1 because a confident wrong prediction has
    infinite loss, and one such patient would make the whole average
    infinite regardless of the other three thousand nine hundred.
    """
    probability = np.clip(probability, eps, 1 - eps)
    return float(-np.mean(y * np.log(probability)
                          + (1 - y) * np.log(1 - probability)))


def fit_logistic(x: np.ndarray, y: np.ndarray, learning_rate: float = 0.5,
                 iterations: int = 4000, l2: float = 0.0,
                 tolerance: float = 1e-9) -> tuple:
    """Gradient descent on the log-loss. Returns ``(weights, intercept)``.

    The gradient of the log-loss with respect to the linear predictor is
    ``p - y``, which is the same clean form cross-entropy has everywhere
    else - no chain rule through the sigmoid survives into it, because
    the sigmoid's derivative cancels against the log's.

    ``l2`` shrinks the weights towards zero. It is off by default,
    because Day 5's subject is what the coefficients mean and a penalty
    biases them on purpose.
    """
    if learning_rate <= 0:
        raise ValueError(f"learning_rate must be positive, got {learning_rate}")
    if l2 < 0:
        raise ValueError(f"l2 must be non-negative, got {l2}")
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    weights = np.zeros(x.shape[1])
    intercept = 0.0
    previous = float("inf")
    for _ in range(iterations):
        probability = sigmoid(intercept + x @ weights)
        error = probability - y
        gradient = x.T @ error / len(y) + l2 * weights
        intercept -= learning_rate * float(error.mean())
        weights -= learning_rate * gradient
        loss = log_loss(y, probability)
        if abs(previous - loss) < tolerance:
            break
        previous = loss
    return weights, intercept


def predict(x: np.ndarray, weights: np.ndarray, intercept: float) -> np.ndarray:
    """Predicted probability for each row."""
    return sigmoid(intercept + np.asarray(x, dtype=float) @ weights)


def odds_ratio(coefficient: float) -> float:
    """exp(coefficient): the multiplier on the ODDS per unit of the feature.

    The reason a logistic coefficient is quotable at all. A coefficient
    of 0.80 for smoking means a smoker's odds are ``exp(0.80) = 2.23``
    times a non-smoker's, all else equal - which is a sentence a clinician
    can check against their own experience, and a random forest cannot
    produce.

    Note **odds**, not risk. At low risk the two are close; at high risk
    they diverge badly, and the demo shows by how much.

    >>> round(odds_ratio(0.8), 3)
    2.226
    """
    return float(np.exp(coefficient))


def risk_ratio(coefficient: float, baseline_risk: float) -> float:
    """How much the RISK multiplies, which depends on where you start.

    The number people hear when they are told an odds ratio.
    """
    if not 0 < baseline_risk < 1:
        raise ValueError(f"baseline_risk must be in (0,1), got {baseline_risk}")
    baseline_odds = baseline_risk / (1 - baseline_risk)
    new_odds = baseline_odds * np.exp(coefficient)
    new_risk = new_odds / (1 + new_odds)
    return float(new_risk / baseline_risk)


def recovery_error(fitted: np.ndarray, truth: dict | None = None) -> dict:
    """Absolute error between each fitted coefficient and the one used."""
    truth = truth or TRUE_COEFFICIENTS
    return {name: abs(fitted[index] - truth[name])
            for index, name in enumerate(FEATURE_NAMES)}


def coefficient_spread(n: int, correlate_cholesterol: float = 0.0,
                       repeats: int = 40, index: int = 0) -> dict:
    """Refit on many independent cohorts and report the spread of one weight.

    The only honest way to talk about what a coefficient "is" from a
    single study: draw the study again and see what else it might have
    said.
    """
    values = []
    for seed in range(repeats):
        cohort = make_cohort(n=n, seed=seed,
                             correlate_cholesterol=correlate_cholesterol)
        weights, _ = fit_logistic(cohort.x, cohort.y, iterations=4000)
        values.append(weights[index])
    values = np.array(values)
    return {"mean": float(values.mean()), "sd": float(values.std()),
            "min": float(values.min()), "max": float(values.max())}


# --- Day 6 -----------------------------------------------------------------


@dataclass(frozen=True)
class Confusion:
    """The four counts everything else on this day is arithmetic over."""

    true_positive: int
    false_positive: int
    true_negative: int
    false_negative: int

    @property
    def total(self) -> int:
        return (self.true_positive + self.false_positive
                + self.true_negative + self.false_negative)

    @property
    def positives(self) -> int:
        return self.true_positive + self.false_negative

    @property
    def prevalence(self) -> float:
        return self.positives / self.total if self.total else 0.0


def confusion(y: np.ndarray, predicted: np.ndarray) -> Confusion:
    """Count the four outcomes.

    >>> confusion(np.array([1, 0]), np.array([1, 1])).false_positive
    1
    """
    y = np.asarray(y).astype(bool)
    predicted = np.asarray(predicted).astype(bool)
    return Confusion(
        true_positive=int(np.sum(y & predicted)),
        false_positive=int(np.sum(~y & predicted)),
        true_negative=int(np.sum(~y & ~predicted)),
        false_negative=int(np.sum(y & ~predicted)),
    )


def accuracy(matrix: Confusion) -> float:
    """Fraction of patients classified correctly.

    The number that sounds like it answers the question and does not.
    A model predicting "no event" for everyone scores ``1 - prevalence``,
    which at a 5% event rate is 95% - and the demo shows what that model
    is worth.
    """
    if not matrix.total:
        return 0.0
    return (matrix.true_positive + matrix.true_negative) / matrix.total


def sensitivity(matrix: Confusion) -> float:
    """Of the patients who had the event, the fraction found.

    A property of the test on diseased patients only, so it does not
    move when prevalence does. Also called recall.
    """
    if not matrix.positives:
        return 0.0
    return matrix.true_positive / matrix.positives


def specificity(matrix: Confusion) -> float:
    """Of the patients who did not, the fraction correctly cleared."""
    negatives = matrix.true_negative + matrix.false_positive
    if not negatives:
        return 0.0
    return matrix.true_negative / negatives


def ppv(matrix: Confusion) -> float:
    """Of the patients flagged, the fraction who really had the event.

    The number the patient in front of you actually cares about, and the
    only one of the four that **depends on prevalence**. The same test,
    unchanged, has a different PPV in a screening clinic than in a
    referral centre, and that is not a flaw in the test.
    """
    flagged = matrix.true_positive + matrix.false_positive
    if not flagged:
        return 0.0
    return matrix.true_positive / flagged


def npv(matrix: Confusion) -> float:
    """Of the patients cleared, the fraction who really were well."""
    cleared = matrix.true_negative + matrix.false_negative
    if not cleared:
        return 0.0
    return matrix.true_negative / cleared


def ppv_from_rates(sensitivity_value: float, specificity_value: float,
                   prevalence: float) -> float:
    """PPV computed from the two stable rates and the prevalence.

    Bayes' rule, and the cleanest statement of the day: sensitivity and
    specificity are properties of the test, prevalence is a property of
    the population, and **PPV is a property of both**. A paper reporting
    only the first two has told you nothing about what a positive result
    means in your clinic.

    >>> round(ppv_from_rates(0.95, 0.95, 0.01), 4)
    0.1610
    """
    for name, value in (("sensitivity", sensitivity_value),
                        ("specificity", specificity_value),
                        ("prevalence", prevalence)):
        if not 0 <= value <= 1:
            raise ValueError(f"{name} must be between 0 and 1, got {value}")
    true_positive = sensitivity_value * prevalence
    false_positive = (1 - specificity_value) * (1 - prevalence)
    if true_positive + false_positive == 0:
        return 0.0
    return true_positive / (true_positive + false_positive)


def false_alarms_per_case(sensitivity_value: float, specificity_value: float,
                          prevalence: float) -> float:
    """How many people are wrongly flagged for each one correctly flagged.

    The same fact as PPV, in the unit a clinic feels: every one of these
    is a person who gets a phone call, an appointment and a week of worry
    for nothing.
    """
    value = ppv_from_rates(sensitivity_value, specificity_value, prevalence)
    if value <= 0:
        return float("inf")
    return (1 - value) / value


def number_needed_to_screen(sensitivity_value: float, prevalence: float) -> float:
    """Patients screened per true case found."""
    if prevalence <= 0 or sensitivity_value <= 0:
        return float("inf")
    return 1.0 / (prevalence * sensitivity_value)


def always_negative_accuracy(prevalence: float) -> float:
    """The accuracy of predicting "no event" for everybody.

    The baseline every accuracy figure has to beat before it means
    anything, and the one most papers do not print.
    """
    return 1.0 - prevalence


def report(y: np.ndarray, predicted: np.ndarray) -> dict:
    """Every rate at once, from one set of predictions."""
    matrix = confusion(y, predicted)
    return {"accuracy": accuracy(matrix), "sensitivity": sensitivity(matrix),
            "specificity": specificity(matrix), "ppv": ppv(matrix),
            "npv": npv(matrix), "prevalence": matrix.prevalence,
            "flagged": matrix.true_positive + matrix.false_positive}


def auc(y: np.ndarray, score: np.ndarray) -> float:
    """Probability that a random case outranks a random control.

    A **ranking** measure, so it never looks at the threshold. That makes
    it the one number on this day that does not move when prevalence
    does - and also the one that cannot tell you what a positive result
    means for the patient in front of you.

    >>> round(auc(np.array([0, 0, 1, 1]), np.array([0.1, 0.2, 0.3, 0.4])), 3)
    1.0
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    positives, negatives = float(y.sum()), float((1 - y).sum())
    if positives == 0 or negatives == 0:
        return 0.5
    order = np.argsort(score)
    ranks = np.empty(len(score), dtype=float)
    ranks[order] = np.arange(1, len(score) + 1)
    return float((ranks[y == 1].sum() - positives * (positives + 1) / 2)
                 / (positives * negatives))


# --- Day 7 -----------------------------------------------------------------


def roc_curve(y: np.ndarray, score: np.ndarray) -> tuple:
    """False-positive rate, true-positive rate, and the threshold at each.

    Swept over every distinct score, so the curve is exact rather than
    sampled at a few round numbers.
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    thresholds = np.unique(score)[::-1]
    positives, negatives = float(y.sum()), float((1 - y).sum())
    if positives == 0 or negatives == 0:
        raise ValueError("need both classes present to draw an ROC curve")
    true_positive_rate, false_positive_rate = [], []
    for threshold in thresholds:
        flagged = score >= threshold
        true_positive_rate.append(float(np.sum(flagged & (y == 1)) / positives))
        false_positive_rate.append(float(np.sum(flagged & (y == 0)) / negatives))
    return (np.array(false_positive_rate), np.array(true_positive_rate),
            thresholds)


def precision_recall_curve(y: np.ndarray, score: np.ndarray) -> tuple:
    """Precision and recall at every threshold.

    Worth drawing alongside the ROC because the two disagree about how
    good a model is at low prevalence: the ROC's false-positive rate has
    the large well population in its denominator, so a great many false
    alarms barely move it, while precision has only the flagged patients
    in its denominator and notices immediately.
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    thresholds = np.unique(score)[::-1]
    positives = float(y.sum())
    precision, recall = [], []
    for threshold in thresholds:
        flagged = score >= threshold
        hits = float(np.sum(flagged & (y == 1)))
        precision.append(hits / max(float(flagged.sum()), 1.0))
        recall.append(hits / positives if positives else 0.0)
    return np.array(precision), np.array(recall), thresholds


def threshold_at_half(y: np.ndarray, score: np.ndarray) -> float:
    """0.5, the default nobody chooses on purpose."""
    return 0.5


def youden_threshold(y: np.ndarray, score: np.ndarray) -> float:
    """The threshold maximising ``sensitivity + specificity - 1``.

    The most common "principled" choice, and it is principled about one
    thing only: it weights a miss and a false alarm equally **per
    patient of that class**, which is not the same as weighting them
    equally per patient, and is almost never what a clinic means.
    """
    false_positive_rate, true_positive_rate, thresholds = roc_curve(y, score)
    return float(thresholds[int(np.argmax(true_positive_rate - false_positive_rate))])


def f1_threshold(y: np.ndarray, score: np.ndarray) -> float:
    """The threshold maximising the harmonic mean of precision and recall.

    Popular, and it has no clinical interpretation at all: there is no
    cost ratio under which maximising F1 is the right decision, because
    F1 is not a linear function of the four counts.
    """
    precision, recall, thresholds = precision_recall_curve(y, score)
    denominator = precision + recall
    f1 = np.where(denominator > 0, 2 * precision * recall / np.maximum(denominator, 1e-12), 0.0)
    return float(thresholds[int(np.argmax(f1))])


def cost_threshold(y: np.ndarray, score: np.ndarray, miss_cost: float,
                   false_alarm_cost: float) -> float:
    """The threshold minimising total cost, given what the two errors cost.

    The only one of these four that answers a question somebody asked.
    ``miss_cost`` is what happens when a case goes home undiagnosed;
    ``false_alarm_cost`` is the biopsy, the anxiety, the wasted clinic
    slot. Their ratio is the whole input - doubling both changes nothing.
    """
    if miss_cost <= 0 or false_alarm_cost <= 0:
        raise ValueError("both costs must be positive")
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    thresholds = np.unique(score)[::-1]
    best, best_cost = 0.5, float("inf")
    for threshold in thresholds:
        flagged = score >= threshold
        misses = float(np.sum(~flagged & (y == 1)))
        alarms = float(np.sum(flagged & (y == 0)))
        cost = miss_cost * misses + false_alarm_cost * alarms
        if cost < best_cost:
            best, best_cost = float(threshold), cost
    return best


def implied_cost_ratio(threshold: float) -> float:
    """The miss-to-false-alarm cost ratio a threshold assumes.

    The point of the day. Expected cost is minimised by flagging a
    patient when ``p * miss_cost > (1 - p) * false_alarm_cost``, so the
    optimal threshold is ``t = c / (c + 1)`` for a cost ratio ``c`` — and
    reading that backwards, **any threshold is a statement about costs**:

        c = t / (1 - t)

    A threshold of 0.5 says a miss and a false alarm cost the same. A
    threshold of 0.1 says a miss costs nine times as much. Nobody
    choosing 0.5 says the first sentence out loud, and it is what they
    have committed to.

    Returns miss cost divided by false-alarm cost, which is
    ``(1 - t) / t`` and is the exact inverse of
    ``threshold_for_cost_ratio``. The first version of this returned
    ``t / (1 - t)`` - the reciprocal - so the number disagreed with both
    the function's name and the sentence above it, and a round trip
    through the two functions did not come back.

    >>> round(implied_cost_ratio(0.5), 6)
    1.0
    >>> round(implied_cost_ratio(0.1), 6)
    9.0
    """
    if not 0 < threshold < 1:
        raise ValueError(f"threshold must be in (0,1), got {threshold}")
    return (1 - threshold) / threshold


def threshold_for_cost_ratio(miss_cost: float, false_alarm_cost: float) -> float:
    """The threshold implied by a cost ratio. The inverse of the above.

    >>> round(threshold_for_cost_ratio(9.0, 1.0), 4)
    0.1
    """
    if miss_cost <= 0 or false_alarm_cost <= 0:
        raise ValueError("both costs must be positive")
    ratio = false_alarm_cost / miss_cost
    return ratio / (1 + ratio)


def total_cost(y: np.ndarray, score: np.ndarray, threshold: float,
               miss_cost: float, false_alarm_cost: float) -> float:
    """What a threshold costs on this cohort, in the caller's units."""
    flagged = np.asarray(score) >= threshold
    y = np.asarray(y)
    misses = float(np.sum(~flagged & (y == 1)))
    alarms = float(np.sum(flagged & (y == 0)))
    return miss_cost * misses + false_alarm_cost * alarms


# --- Day 8 -----------------------------------------------------------------


def reliability(y: np.ndarray, probability: np.ndarray, bins: int = 10) -> list:
    """Group patients by predicted risk and count what actually happened.

    The reliability diagram, as a table. For each bin: how many patients,
    what the model promised on average, and what fraction of them had the
    event. A calibrated model puts those last two columns on top of each
    other.

    Bins are fixed-width over [0, 1] rather than equal-count, because
    equal-count bins hide the region where a model is most confident and
    most wrong - which is where the interesting failure lives.
    """
    if bins < 1:
        raise ValueError(f"bins must be at least 1, got {bins}")
    y = np.asarray(y, dtype=float)
    probability = np.asarray(probability, dtype=float)
    edges = np.linspace(0.0, 1.0, bins + 1)
    rows = []
    for index in range(bins):
        low, high = edges[index], edges[index + 1]
        inside = (probability >= low) & (probability < high if index < bins - 1
                                         else probability <= high)
        count = int(inside.sum())
        if not count:
            rows.append({"low": float(low), "high": float(high), "count": 0,
                         "predicted": float("nan"), "observed": float("nan")})
            continue
        rows.append({"low": float(low), "high": float(high), "count": count,
                     "predicted": float(probability[inside].mean()),
                     "observed": float(y[inside].mean())})
    return rows


def expected_calibration_error(y: np.ndarray, probability: np.ndarray,
                               bins: int = 10) -> float:
    """Average gap between promised and observed risk, weighted by bin size.

    One number for a reliability diagram. It is a weighted mean absolute
    error, so it cannot distinguish a model that is uniformly 5% too
    confident from one that is 20% wrong in one bin and right everywhere
    else - the demo shows both and says which is which.
    """
    rows = reliability(y, probability, bins=bins)
    total = sum(row["count"] for row in rows)
    if not total:
        return 0.0
    return float(sum(row["count"] * abs(row["predicted"] - row["observed"])
                     for row in rows if row["count"]) / total)


def brier_score(y: np.ndarray, probability: np.ndarray) -> float:
    """Mean squared error of the predicted probabilities.

    Unlike AUC it is a **proper scoring rule**: it is minimised only by
    reporting your true belief, so a model cannot improve it by shading
    its predictions towards the middle or the extremes.

    >>> round(brier_score(np.array([1.0, 0.0]), np.array([1.0, 0.0])), 6)
    0.0
    """
    y = np.asarray(y, dtype=float)
    probability = np.asarray(probability, dtype=float)
    return float(np.mean((probability - y) ** 2))


def brier_decomposition(y: np.ndarray, probability: np.ndarray,
                        bins: int = 10) -> dict:
    """Split the Brier score into reliability, resolution and uncertainty.

        Brier = reliability - resolution + uncertainty

    **Reliability** is the calibration error (lower is better).
    **Resolution** is how far the bins' outcome rates sit from the base
    rate — how much the model actually distinguishes patients (higher is
    better). **Uncertainty** is the base rate's own variance, which no
    model can change.

    The decomposition is the cleanest statement of what this day is
    about: calibration and discrimination are *separate terms*, and a
    model can be good at one while being poor at the other.
    """
    y = np.asarray(y, dtype=float)
    rows = reliability(y, probability, bins=bins)
    total = len(y)
    base_rate = float(y.mean())
    reliability_term = 0.0
    resolution_term = 0.0
    for row in rows:
        if not row["count"]:
            continue
        weight = row["count"] / total
        reliability_term += weight * (row["predicted"] - row["observed"]) ** 2
        resolution_term += weight * (row["observed"] - base_rate) ** 2
    uncertainty = base_rate * (1 - base_rate)
    return {"reliability": reliability_term, "resolution": resolution_term,
            "uncertainty": uncertainty,
            "brier": reliability_term - resolution_term + uncertainty}


def miscalibrate(probability: np.ndarray, power: float = 1.0,
                 shift: float = 0.0) -> np.ndarray:
    """Distort probabilities without changing their order.

    ``power`` raises the odds to a power - over-confident above 1, under
    below - and ``shift`` multiplies the odds by a constant. Both are
    strictly monotone, so **AUC is untouched by construction** and any
    change in calibration is the whole effect.

    This is the instrument for the day's central claim, and the reason it
    is a claim rather than an anecdote.
    """
    probability = np.clip(np.asarray(probability, dtype=float), 1e-12, 1 - 1e-12)
    odds = probability / (1 - probability)
    distorted = np.exp(shift) * odds ** power
    return distorted / (1 + distorted)


def platt_scale(probability: np.ndarray, y: np.ndarray,
                iterations: int = 2000) -> tuple:
    """Fit ``sigmoid(a * logit(p) + b)`` to repair calibration.

    One-dimensional logistic regression on the model's own log-odds. It
    is monotone, so it cannot change the ranking and therefore cannot
    change the AUC - which is exactly the property that makes it a
    calibration fix rather than a new model.
    """
    probability = np.clip(np.asarray(probability, dtype=float), 1e-12, 1 - 1e-12)
    logit = np.log(probability / (1 - probability)).reshape(-1, 1)
    weights, intercept = fit_logistic(logit, np.asarray(y, dtype=float),
                                      iterations=iterations)
    return float(weights[0]), float(intercept)


def apply_platt(probability: np.ndarray, slope: float, intercept: float) -> np.ndarray:
    probability = np.clip(np.asarray(probability, dtype=float), 1e-12, 1 - 1e-12)
    logit = np.log(probability / (1 - probability))
    return sigmoid(slope * logit + intercept)


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every patient here is generated by this file.")

    cohort = make_cohort(n=40000, seed=0, prevalence=0.12)
    weights, intercept = fit_logistic(cohort.x, cohort.y)
    probability = predict(cohort.x, weights, intercept)
    print()
    print(f"cohort {len(cohort)}, prevalence {cohort.prevalence:.1%}, "
          f"AUC {auc(cohort.y, probability):.3f}")

    print()
    print("=" * 74)
    print("1. does 30% mean 30%?")
    print("=" * 74)
    print(f"  {'predicted risk':>16}{'patients':>10}{'promised':>11}"
          f"{'happened':>11}{'gap':>9}")
    for row in reliability(cohort.y, probability, bins=10):
        if not row["count"]:
            continue
        label = "%.0f%%-%.0f%%" % (row["low"] * 100, row["high"] * 100)
        print(f"  {label:>16}{row['count']:>10}{row['predicted']:>11.3f}"
              f"{row['observed']:>11.3f}{row['predicted'] - row['observed']:>9.3f}")
    print()
    print(f"  ECE {expected_calibration_error(cohort.y, probability):.4f}, "
          f"Brier {brier_score(cohort.y, probability):.4f}")
    print()
    print("  the model is very well calibrated, and it should be: Day 5")
    print("  generated this cohort from a logistic model and Day 5's fit is a")
    print("  logistic model, so the family is exactly right. That is a")
    print("  property of the experiment rather than an achievement.")
    print()
    print("  the last two bins are off by 0.19 and 0.32 - on eighteen")
    print("  patients and four. A reliability diagram is a set of small")
    print("  samples in its tails, and those bins say nothing.")

    print()
    print("=" * 74)
    print("2. calibration and discrimination are independent")
    print("=" * 74)
    print("  distort the probabilities while preserving their ORDER. Any")
    print("  monotone transform leaves the ranking alone, so AUC cannot move")
    print("  by construction:")
    print()
    print(f"  {'distortion':<30}{'AUC':>9}{'ECE':>9}{'Brier':>9}")
    distortions = (
        ("none", probability),
        ("over-confident, odds^1.6", miscalibrate(probability, power=1.6)),
        ("under-confident, odds^0.5", miscalibrate(probability, power=0.5)),
        ("shifted up, odds x 3", miscalibrate(probability, shift=float(np.log(3)))),
        ("shifted down, odds x 1/3", miscalibrate(probability, shift=-float(np.log(3)))),
    )
    for name, distorted in distortions:
        print(f"  {name:<30}{auc(cohort.y, distorted):>9.4f}"
              f"{expected_calibration_error(cohort.y, distorted):>9.4f}"
              f"{brier_score(cohort.y, distorted):>9.4f}")
    print()
    print("  the AUC column is one number repeated five times, to four")
    print("  decimal places, while the calibration error moves by a factor of")
    print("  a hundred.")
    print()
    print("  so a paper reporting AUC 0.74 has said nothing whatsoever about")
    print("  whether its 30% means 30%. The two are not correlated, not")
    print("  loosely related, not usually similar - AUC is a function of the")
    print("  ORDER of the predictions and calibration is a function of their")
    print("  VALUES, and the transform above changes one without touching the")
    print("  other.")

    print()
    print("=" * 74)
    print("3. which is why the Brier score is the more honest number")
    print("=" * 74)
    print("  Brier = reliability - resolution + uncertainty")
    print()
    broken = miscalibrate(probability, power=1.6, shift=float(np.log(2.5)))
    slope, offset = platt_scale(broken, cohort.y)
    repaired = apply_platt(broken, slope, offset)
    print(f"  {'':<16}{'reliability':>13}{'resolution':>12}"
          f"{'uncertainty':>13}{'Brier':>9}")
    for name, series in (("original", probability), ("distorted", broken),
                         ("repaired", repaired)):
        parts = brier_decomposition(cohort.y, series)
        print(f"  {name:<16}{parts['reliability']:>13.5f}"
              f"{parts['resolution']:>12.5f}{parts['uncertainty']:>13.5f}"
              f"{parts['brier']:>9.5f}")
    print()
    print("  the distortion moved the reliability term by seventy-fold and")
    print("  left resolution and uncertainty where they were. Resolution is")
    print("  discrimination - the same thing AUC measures - and uncertainty")
    print("  belongs to the base rate and no model can touch it.")
    print()
    print("  that is the decomposition earning its place: it separates the")
    print("  part a monotone transform can ruin from the part it cannot.")

    print()
    print("=" * 74)
    print("4. repairing calibration costs nothing that matters")
    print("=" * 74)
    print(f"  {'':<18}{'AUC':>9}{'ECE':>9}{'Brier':>9}")
    for name, series in (("original", probability), ("distorted", broken),
                         ("Platt-repaired", repaired)):
        print(f"  {name:<18}{auc(cohort.y, series):>9.4f}"
              f"{expected_calibration_error(cohort.y, series):>9.4f}"
              f"{brier_score(cohort.y, series):>9.4f}")
    print()
    print(f"  Platt scaling fits sigmoid(a x logit(p) + b), here "
          f"a={slope:.3f}, b={offset:.3f}.")
    print("  It is monotone, so it cannot change the ranking and cannot")
    print("  change the AUC - which is exactly why it is a calibration fix")
    print("  and not a new model. Everything it recovered was thrown away by")
    print("  the distortion and nothing else.")

    print()
    print("=" * 74)
    print("why this matters more than the rest of Level 2")
    print("=" * 74)
    print("  Day 7 chose a threshold from a cost ratio, and that arithmetic")
    print("  assumed the predicted probability was a probability. Run it on")
    print("  the distorted scores and the chosen cut is wrong:")
    print()
    cut = threshold_for_cost_ratio(5.0, 1.0)
    print(f"  the 5:1 cut is {cut:.3f} in every row. Only the scores differ:")
    print()
    print(f"  {'scores':<26}{'ECE':>8}{'sens':>8}{'flagged':>9}{'workload':>10}")
    reference = report(cohort.y, probability >= cut)
    rows = (("well calibrated", probability),
            ("odds^1.6 x 2.5", broken),
            ("odds x 3", miscalibrate(probability, shift=float(np.log(3)))),
            ("odds x 1/3", miscalibrate(probability, shift=-float(np.log(3)))),
            ("odds^0.4", miscalibrate(probability, power=0.4)))
    for name, series in rows:
        scores = report(cohort.y, series >= cut)
        ratio = scores["flagged"] / max(reference["flagged"], 1)
        print(f"  {name:<26}{expected_calibration_error(cohort.y, series):>8.3f}"
              f"{scores['sensitivity']:>8.1%}{scores['flagged']:>9}"
              f"{f'{ratio:.2f}x':>10}")
    print()
    print("  same threshold, same cost belief, same patients, same ranking,")
    print("  same AUC to four decimals - and a clinic seeing between a")
    print("  seventh and four and a half times as many people.")
    print()
    print("  note the second row. That distortion has an ECE of 0.032 and")
    print("  changes the workload by 4%: some miscalibrations happen to be")
    print("  nearly harmless at a particular threshold. Nothing in the AUC,")
    print("  and nothing in the ECE alone, says which kind you have - it")
    print("  depends on where the distortion bites relative to your cut.")
    print()
    print("  a miscalibrated model does not merely report the wrong number to")
    print("  the patient. It silently invalidates every decision rule built")
    print("  on top of it, by an amount nobody can predict from the summary")
    print("  statistics.")
    print()
    print("  Day 9 asks what happens when the features those probabilities")
    print("  were computed from are not all there.")
