"""Day 9 — Missing data, and the ways imputation lies.

Three mechanisms - a coin flip, a pattern driven by an observed feature,
and a pattern driven by the value that is gone - and four ways of coping
with each.

**Mean imputation halves the coefficient under MCAR**: 0.162 against a
true 0.300, with nothing informative about the missingness at all. Every
imputed patient is placed at the centre of the distribution, so the
column's spread falls while no signal is added, and a coefficient is a
covariance over a variance.

Conditional imputation recovers it - because age correlates 0.80 with
cholesterol in this cohort. Where the observed features do not predict
the missing one, conditional imputation is mean imputation with extra
steps, and that is measured rather than assumed.

**MNAR's damage is not in the coefficient.** It survives, because the fit
conditions on the other features. Split the patients by whether their
value was kept and it appears: the imputer fills +1.339 where the truth
was +0.721, because the missing values were the low ones and nothing in
the data says so. The patients it invented values for are over-predicted,
and that is invisible in the overall AUC.

**And missingness predicts the outcome.** Under MNAR the patients with no
result have an event rate of 8.3% against 15.3%. Adding an indicator
works and encodes one hospital's ordering habits as if they were biology.
Both halves are true and only the first is usually said.

NOT A MEDICAL DEVICE. Every patient in this repo is generated by it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# --- Day 5 -----------------------------------------------------------------

#: The features of the synthetic cohort, and the coefficients that
#: generated it. Everything in Level 2 is scored against these numbers,
#: for the same reason Day 1 generated its own R peaks: a coefficient
#: estimated from real data can only be compared with somebody else's
#: estimate, and an estimate is not a truth.
TRUE_COEFFICIENTS = {
    "age_decades_over_50": 0.55,
    "systolic_over_120_per_10": 0.35,
    "cholesterol_over_5_per_1": 0.30,
    "smoker": 0.80,
    "diabetic": 0.90,
}

#: With the feature distribution below this gives an event rate near 26%.
#: ``make_cohort`` can solve for a different one - prevalence is the
#: subject of Day 6 and a parameter of Day 7, so it had better be a knob
#: rather than a constant chosen once and described inaccurately.
TRUE_INTERCEPT = -2.6

FEATURE_NAMES = tuple(TRUE_COEFFICIENTS)


@dataclass(frozen=True)
class Cohort:
    """A synthetic patient cohort with a known generating model.

    ``x`` holds the features in ``FEATURE_NAMES`` order, already centred
    on clinically meaningful reference points - age in decades past 50,
    systolic pressure in units of 10 mmHg past 120 - so that a
    coefficient reads as "per decade" rather than "per year" and the
    intercept is the log-odds of a reference patient rather than of a
    newborn with no blood pressure.
    """

    x: np.ndarray
    y: np.ndarray
    risk: np.ndarray
    names: tuple = FEATURE_NAMES

    def __len__(self) -> int:
        return len(self.y)

    @property
    def prevalence(self) -> float:
        return float(self.y.mean())


def sigmoid(z: np.ndarray) -> np.ndarray:
    """1 / (1 + exp(-z)), written so it does not overflow.

    ``exp(800)`` is infinity in float64, and a linear predictor of 800 is
    not unusual once a model is confident. The two-branch form keeps the
    exponent negative on both sides.

    It still **saturates**: this returns exactly 1.0 from z = 37 upward,
    because ``1 + 2.2e-16`` is 1.0 at double precision. Nothing is wrong
    with the arithmetic - the value has simply left the range float64 can
    distinguish from certainty - and it is why ``log_loss`` clips. A
    patient predicted at exactly 1.0 who has no event scores an infinite
    loss, and one of them would make the mean over four thousand patients
    infinite too.

    >>> sigmoid(np.array([0.0])).round(4)
    array([0.5])
    >>> np.isfinite(sigmoid(np.array([-800.0, 800.0]))).all()
    True
    """
    z = np.asarray(z, dtype=float)
    out = np.empty_like(z)
    positive = z >= 0
    out[positive] = 1.0 / (1.0 + np.exp(-z[positive]))
    exponential = np.exp(z[~positive])
    out[~positive] = exponential / (1.0 + exponential)
    return out


def intercept_for_prevalence(prevalence: float, n: int = 20000, seed: int = 0,
                             coefficients: dict | None = None,
                             correlate_cholesterol: float = 0.0) -> float:
    """The intercept that makes the mean true risk equal ``prevalence``.

    Bisection on a large draw. Exists because Day 6 sweeps prevalence and
    Day 7 tunes against it, and hard-coding one intercept and describing
    its consequence from memory is how a comment ends up claiming 12%
    where the data says 26%.
    """
    if not 0 < prevalence < 1:
        raise ValueError(f"prevalence must be in (0,1), got {prevalence}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    features = make_cohort(n=n, seed=seed, coefficients=coefficients,
                           correlate_cholesterol=correlate_cholesterol).x
    linear = features @ weights
    low, high = -20.0, 20.0
    for _ in range(80):
        middle = (low + high) / 2
        if sigmoid(middle + linear).mean() < prevalence:
            low = middle
        else:
            high = middle
    return (low + high) / 2


def make_cohort(n: int = 4000, seed: int = 0,
                coefficients: dict | None = None,
                intercept: float = TRUE_INTERCEPT,
                correlate_cholesterol: float = 0.0,
                prevalence: float | None = None) -> Cohort:
    """Draw patients, compute their true risk, and flip a coin each.

    The outcome is **sampled** from the true risk rather than thresholded
    at it. That distinction is the whole of Day 8: a patient with a 30%
    risk who does not have the event is not a model error, and a dataset
    built by thresholding would make calibration meaningless.

    ``correlate_cholesterol`` makes cholesterol partly a function of age,
    which is true of real cohorts and is what Day 5's last section is
    about.
    """
    if n < 1:
        raise ValueError(f"n must be positive, got {n}")
    coefficients = coefficients or TRUE_COEFFICIENTS
    if prevalence is not None:
        intercept = intercept_for_prevalence(
            prevalence, coefficients=coefficients,
            correlate_cholesterol=correlate_cholesterol)
    rng = np.random.default_rng(seed)

    age_years = rng.normal(58.0, 9.0, size=n)
    age = (age_years - 50.0) / 10.0
    systolic = (rng.normal(132.0, 16.0, size=n) - 120.0) / 10.0
    base_cholesterol = rng.normal(5.4, 1.0, size=n)
    if correlate_cholesterol:
        base_cholesterol = (base_cholesterol
                            + correlate_cholesterol * age * 1.0)
    cholesterol = base_cholesterol - 5.0
    smoker = (rng.random(n) < 0.28).astype(float)
    diabetic = (rng.random(n) < 0.15).astype(float)

    x = np.column_stack([age, systolic, cholesterol, smoker, diabetic])
    weights = np.array([coefficients[name] for name in FEATURE_NAMES])
    risk = sigmoid(intercept + x @ weights)
    y = (rng.random(n) < risk).astype(float)
    return Cohort(x=x, y=y, risk=risk)


def log_loss(y: np.ndarray, probability: np.ndarray, eps: float = 1e-12) -> float:
    """Mean negative log-likelihood, the thing the fit minimises.

    Clipped away from 0 and 1 because a confident wrong prediction has
    infinite loss, and one such patient would make the whole average
    infinite regardless of the other three thousand nine hundred.
    """
    probability = np.clip(probability, eps, 1 - eps)
    return float(-np.mean(y * np.log(probability)
                          + (1 - y) * np.log(1 - probability)))


def fit_logistic(x: np.ndarray, y: np.ndarray, learning_rate: float = 0.5,
                 iterations: int = 4000, l2: float = 0.0,
                 tolerance: float = 1e-9) -> tuple:
    """Gradient descent on the log-loss. Returns ``(weights, intercept)``.

    The gradient of the log-loss with respect to the linear predictor is
    ``p - y``, which is the same clean form cross-entropy has everywhere
    else - no chain rule through the sigmoid survives into it, because
    the sigmoid's derivative cancels against the log's.

    ``l2`` shrinks the weights towards zero. It is off by default,
    because Day 5's subject is what the coefficients mean and a penalty
    biases them on purpose.
    """
    if learning_rate <= 0:
        raise ValueError(f"learning_rate must be positive, got {learning_rate}")
    if l2 < 0:
        raise ValueError(f"l2 must be non-negative, got {l2}")
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    weights = np.zeros(x.shape[1])
    intercept = 0.0
    previous = float("inf")
    for _ in range(iterations):
        probability = sigmoid(intercept + x @ weights)
        error = probability - y
        gradient = x.T @ error / len(y) + l2 * weights
        intercept -= learning_rate * float(error.mean())
        weights -= learning_rate * gradient
        loss = log_loss(y, probability)
        if abs(previous - loss) < tolerance:
            break
        previous = loss
    return weights, intercept


def predict(x: np.ndarray, weights: np.ndarray, intercept: float) -> np.ndarray:
    """Predicted probability for each row."""
    return sigmoid(intercept + np.asarray(x, dtype=float) @ weights)


def odds_ratio(coefficient: float) -> float:
    """exp(coefficient): the multiplier on the ODDS per unit of the feature.

    The reason a logistic coefficient is quotable at all. A coefficient
    of 0.80 for smoking means a smoker's odds are ``exp(0.80) = 2.23``
    times a non-smoker's, all else equal - which is a sentence a clinician
    can check against their own experience, and a random forest cannot
    produce.

    Note **odds**, not risk. At low risk the two are close; at high risk
    they diverge badly, and the demo shows by how much.

    >>> round(odds_ratio(0.8), 3)
    2.226
    """
    return float(np.exp(coefficient))


def risk_ratio(coefficient: float, baseline_risk: float) -> float:
    """How much the RISK multiplies, which depends on where you start.

    The number people hear when they are told an odds ratio.
    """
    if not 0 < baseline_risk < 1:
        raise ValueError(f"baseline_risk must be in (0,1), got {baseline_risk}")
    baseline_odds = baseline_risk / (1 - baseline_risk)
    new_odds = baseline_odds * np.exp(coefficient)
    new_risk = new_odds / (1 + new_odds)
    return float(new_risk / baseline_risk)


def recovery_error(fitted: np.ndarray, truth: dict | None = None) -> dict:
    """Absolute error between each fitted coefficient and the one used."""
    truth = truth or TRUE_COEFFICIENTS
    return {name: abs(fitted[index] - truth[name])
            for index, name in enumerate(FEATURE_NAMES)}


def coefficient_spread(n: int, correlate_cholesterol: float = 0.0,
                       repeats: int = 40, index: int = 0) -> dict:
    """Refit on many independent cohorts and report the spread of one weight.

    The only honest way to talk about what a coefficient "is" from a
    single study: draw the study again and see what else it might have
    said.
    """
    values = []
    for seed in range(repeats):
        cohort = make_cohort(n=n, seed=seed,
                             correlate_cholesterol=correlate_cholesterol)
        weights, _ = fit_logistic(cohort.x, cohort.y, iterations=4000)
        values.append(weights[index])
    values = np.array(values)
    return {"mean": float(values.mean()), "sd": float(values.std()),
            "min": float(values.min()), "max": float(values.max())}


# --- Day 6 -----------------------------------------------------------------


@dataclass(frozen=True)
class Confusion:
    """The four counts everything else on this day is arithmetic over."""

    true_positive: int
    false_positive: int
    true_negative: int
    false_negative: int

    @property
    def total(self) -> int:
        return (self.true_positive + self.false_positive
                + self.true_negative + self.false_negative)

    @property
    def positives(self) -> int:
        return self.true_positive + self.false_negative

    @property
    def prevalence(self) -> float:
        return self.positives / self.total if self.total else 0.0


def confusion(y: np.ndarray, predicted: np.ndarray) -> Confusion:
    """Count the four outcomes.

    >>> confusion(np.array([1, 0]), np.array([1, 1])).false_positive
    1
    """
    y = np.asarray(y).astype(bool)
    predicted = np.asarray(predicted).astype(bool)
    return Confusion(
        true_positive=int(np.sum(y & predicted)),
        false_positive=int(np.sum(~y & predicted)),
        true_negative=int(np.sum(~y & ~predicted)),
        false_negative=int(np.sum(y & ~predicted)),
    )


def accuracy(matrix: Confusion) -> float:
    """Fraction of patients classified correctly.

    The number that sounds like it answers the question and does not.
    A model predicting "no event" for everyone scores ``1 - prevalence``,
    which at a 5% event rate is 95% - and the demo shows what that model
    is worth.
    """
    if not matrix.total:
        return 0.0
    return (matrix.true_positive + matrix.true_negative) / matrix.total


def sensitivity(matrix: Confusion) -> float:
    """Of the patients who had the event, the fraction found.

    A property of the test on diseased patients only, so it does not
    move when prevalence does. Also called recall.
    """
    if not matrix.positives:
        return 0.0
    return matrix.true_positive / matrix.positives


def specificity(matrix: Confusion) -> float:
    """Of the patients who did not, the fraction correctly cleared."""
    negatives = matrix.true_negative + matrix.false_positive
    if not negatives:
        return 0.0
    return matrix.true_negative / negatives


def ppv(matrix: Confusion) -> float:
    """Of the patients flagged, the fraction who really had the event.

    The number the patient in front of you actually cares about, and the
    only one of the four that **depends on prevalence**. The same test,
    unchanged, has a different PPV in a screening clinic than in a
    referral centre, and that is not a flaw in the test.
    """
    flagged = matrix.true_positive + matrix.false_positive
    if not flagged:
        return 0.0
    return matrix.true_positive / flagged


def npv(matrix: Confusion) -> float:
    """Of the patients cleared, the fraction who really were well."""
    cleared = matrix.true_negative + matrix.false_negative
    if not cleared:
        return 0.0
    return matrix.true_negative / cleared


def ppv_from_rates(sensitivity_value: float, specificity_value: float,
                   prevalence: float) -> float:
    """PPV computed from the two stable rates and the prevalence.

    Bayes' rule, and the cleanest statement of the day: sensitivity and
    specificity are properties of the test, prevalence is a property of
    the population, and **PPV is a property of both**. A paper reporting
    only the first two has told you nothing about what a positive result
    means in your clinic.

    >>> round(ppv_from_rates(0.95, 0.95, 0.01), 4)
    0.1610
    """
    for name, value in (("sensitivity", sensitivity_value),
                        ("specificity", specificity_value),
                        ("prevalence", prevalence)):
        if not 0 <= value <= 1:
            raise ValueError(f"{name} must be between 0 and 1, got {value}")
    true_positive = sensitivity_value * prevalence
    false_positive = (1 - specificity_value) * (1 - prevalence)
    if true_positive + false_positive == 0:
        return 0.0
    return true_positive / (true_positive + false_positive)


def false_alarms_per_case(sensitivity_value: float, specificity_value: float,
                          prevalence: float) -> float:
    """How many people are wrongly flagged for each one correctly flagged.

    The same fact as PPV, in the unit a clinic feels: every one of these
    is a person who gets a phone call, an appointment and a week of worry
    for nothing.
    """
    value = ppv_from_rates(sensitivity_value, specificity_value, prevalence)
    if value <= 0:
        return float("inf")
    return (1 - value) / value


def number_needed_to_screen(sensitivity_value: float, prevalence: float) -> float:
    """Patients screened per true case found."""
    if prevalence <= 0 or sensitivity_value <= 0:
        return float("inf")
    return 1.0 / (prevalence * sensitivity_value)


def always_negative_accuracy(prevalence: float) -> float:
    """The accuracy of predicting "no event" for everybody.

    The baseline every accuracy figure has to beat before it means
    anything, and the one most papers do not print.
    """
    return 1.0 - prevalence


def report(y: np.ndarray, predicted: np.ndarray) -> dict:
    """Every rate at once, from one set of predictions."""
    matrix = confusion(y, predicted)
    return {"accuracy": accuracy(matrix), "sensitivity": sensitivity(matrix),
            "specificity": specificity(matrix), "ppv": ppv(matrix),
            "npv": npv(matrix), "prevalence": matrix.prevalence,
            "flagged": matrix.true_positive + matrix.false_positive}


def auc(y: np.ndarray, score: np.ndarray) -> float:
    """Probability that a random case outranks a random control.

    A **ranking** measure, so it never looks at the threshold. That makes
    it the one number on this day that does not move when prevalence
    does - and also the one that cannot tell you what a positive result
    means for the patient in front of you.

    >>> round(auc(np.array([0, 0, 1, 1]), np.array([0.1, 0.2, 0.3, 0.4])), 3)
    1.0
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    positives, negatives = float(y.sum()), float((1 - y).sum())
    if positives == 0 or negatives == 0:
        return 0.5
    order = np.argsort(score)
    ranks = np.empty(len(score), dtype=float)
    ranks[order] = np.arange(1, len(score) + 1)
    return float((ranks[y == 1].sum() - positives * (positives + 1) / 2)
                 / (positives * negatives))


# --- Day 7 -----------------------------------------------------------------


def roc_curve(y: np.ndarray, score: np.ndarray) -> tuple:
    """False-positive rate, true-positive rate, and the threshold at each.

    Swept over every distinct score, so the curve is exact rather than
    sampled at a few round numbers.
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    thresholds = np.unique(score)[::-1]
    positives, negatives = float(y.sum()), float((1 - y).sum())
    if positives == 0 or negatives == 0:
        raise ValueError("need both classes present to draw an ROC curve")
    true_positive_rate, false_positive_rate = [], []
    for threshold in thresholds:
        flagged = score >= threshold
        true_positive_rate.append(float(np.sum(flagged & (y == 1)) / positives))
        false_positive_rate.append(float(np.sum(flagged & (y == 0)) / negatives))
    return (np.array(false_positive_rate), np.array(true_positive_rate),
            thresholds)


def precision_recall_curve(y: np.ndarray, score: np.ndarray) -> tuple:
    """Precision and recall at every threshold.

    Worth drawing alongside the ROC because the two disagree about how
    good a model is at low prevalence: the ROC's false-positive rate has
    the large well population in its denominator, so a great many false
    alarms barely move it, while precision has only the flagged patients
    in its denominator and notices immediately.
    """
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    thresholds = np.unique(score)[::-1]
    positives = float(y.sum())
    precision, recall = [], []
    for threshold in thresholds:
        flagged = score >= threshold
        hits = float(np.sum(flagged & (y == 1)))
        precision.append(hits / max(float(flagged.sum()), 1.0))
        recall.append(hits / positives if positives else 0.0)
    return np.array(precision), np.array(recall), thresholds


def threshold_at_half(y: np.ndarray, score: np.ndarray) -> float:
    """0.5, the default nobody chooses on purpose."""
    return 0.5


def youden_threshold(y: np.ndarray, score: np.ndarray) -> float:
    """The threshold maximising ``sensitivity + specificity - 1``.

    The most common "principled" choice, and it is principled about one
    thing only: it weights a miss and a false alarm equally **per
    patient of that class**, which is not the same as weighting them
    equally per patient, and is almost never what a clinic means.
    """
    false_positive_rate, true_positive_rate, thresholds = roc_curve(y, score)
    return float(thresholds[int(np.argmax(true_positive_rate - false_positive_rate))])


def f1_threshold(y: np.ndarray, score: np.ndarray) -> float:
    """The threshold maximising the harmonic mean of precision and recall.

    Popular, and it has no clinical interpretation at all: there is no
    cost ratio under which maximising F1 is the right decision, because
    F1 is not a linear function of the four counts.
    """
    precision, recall, thresholds = precision_recall_curve(y, score)
    denominator = precision + recall
    f1 = np.where(denominator > 0, 2 * precision * recall / np.maximum(denominator, 1e-12), 0.0)
    return float(thresholds[int(np.argmax(f1))])


def cost_threshold(y: np.ndarray, score: np.ndarray, miss_cost: float,
                   false_alarm_cost: float) -> float:
    """The threshold minimising total cost, given what the two errors cost.

    The only one of these four that answers a question somebody asked.
    ``miss_cost`` is what happens when a case goes home undiagnosed;
    ``false_alarm_cost`` is the biopsy, the anxiety, the wasted clinic
    slot. Their ratio is the whole input - doubling both changes nothing.
    """
    if miss_cost <= 0 or false_alarm_cost <= 0:
        raise ValueError("both costs must be positive")
    y = np.asarray(y)
    score = np.asarray(score, dtype=float)
    thresholds = np.unique(score)[::-1]
    best, best_cost = 0.5, float("inf")
    for threshold in thresholds:
        flagged = score >= threshold
        misses = float(np.sum(~flagged & (y == 1)))
        alarms = float(np.sum(flagged & (y == 0)))
        cost = miss_cost * misses + false_alarm_cost * alarms
        if cost < best_cost:
            best, best_cost = float(threshold), cost
    return best


def implied_cost_ratio(threshold: float) -> float:
    """The miss-to-false-alarm cost ratio a threshold assumes.

    The point of the day. Expected cost is minimised by flagging a
    patient when ``p * miss_cost > (1 - p) * false_alarm_cost``, so the
    optimal threshold is ``t = c / (c + 1)`` for a cost ratio ``c`` — and
    reading that backwards, **any threshold is a statement about costs**:

        c = t / (1 - t)

    A threshold of 0.5 says a miss and a false alarm cost the same. A
    threshold of 0.1 says a miss costs nine times as much. Nobody
    choosing 0.5 says the first sentence out loud, and it is what they
    have committed to.

    Returns miss cost divided by false-alarm cost, which is
    ``(1 - t) / t`` and is the exact inverse of
    ``threshold_for_cost_ratio``. The first version of this returned
    ``t / (1 - t)`` - the reciprocal - so the number disagreed with both
    the function's name and the sentence above it, and a round trip
    through the two functions did not come back.

    >>> round(implied_cost_ratio(0.5), 6)
    1.0
    >>> round(implied_cost_ratio(0.1), 6)
    9.0
    """
    if not 0 < threshold < 1:
        raise ValueError(f"threshold must be in (0,1), got {threshold}")
    return (1 - threshold) / threshold


def threshold_for_cost_ratio(miss_cost: float, false_alarm_cost: float) -> float:
    """The threshold implied by a cost ratio. The inverse of the above.

    >>> round(threshold_for_cost_ratio(9.0, 1.0), 4)
    0.1
    """
    if miss_cost <= 0 or false_alarm_cost <= 0:
        raise ValueError("both costs must be positive")
    ratio = false_alarm_cost / miss_cost
    return ratio / (1 + ratio)


def total_cost(y: np.ndarray, score: np.ndarray, threshold: float,
               miss_cost: float, false_alarm_cost: float) -> float:
    """What a threshold costs on this cohort, in the caller's units."""
    flagged = np.asarray(score) >= threshold
    y = np.asarray(y)
    misses = float(np.sum(~flagged & (y == 1)))
    alarms = float(np.sum(flagged & (y == 0)))
    return miss_cost * misses + false_alarm_cost * alarms


# --- Day 8 -----------------------------------------------------------------


def reliability(y: np.ndarray, probability: np.ndarray, bins: int = 10) -> list:
    """Group patients by predicted risk and count what actually happened.

    The reliability diagram, as a table. For each bin: how many patients,
    what the model promised on average, and what fraction of them had the
    event. A calibrated model puts those last two columns on top of each
    other.

    Bins are fixed-width over [0, 1] rather than equal-count, because
    equal-count bins hide the region where a model is most confident and
    most wrong - which is where the interesting failure lives.
    """
    if bins < 1:
        raise ValueError(f"bins must be at least 1, got {bins}")
    y = np.asarray(y, dtype=float)
    probability = np.asarray(probability, dtype=float)
    edges = np.linspace(0.0, 1.0, bins + 1)
    rows = []
    for index in range(bins):
        low, high = edges[index], edges[index + 1]
        inside = (probability >= low) & (probability < high if index < bins - 1
                                         else probability <= high)
        count = int(inside.sum())
        if not count:
            rows.append({"low": float(low), "high": float(high), "count": 0,
                         "predicted": float("nan"), "observed": float("nan")})
            continue
        rows.append({"low": float(low), "high": float(high), "count": count,
                     "predicted": float(probability[inside].mean()),
                     "observed": float(y[inside].mean())})
    return rows


def expected_calibration_error(y: np.ndarray, probability: np.ndarray,
                               bins: int = 10) -> float:
    """Average gap between promised and observed risk, weighted by bin size.

    One number for a reliability diagram. It is a weighted mean absolute
    error, so it cannot distinguish a model that is uniformly 5% too
    confident from one that is 20% wrong in one bin and right everywhere
    else - the demo shows both and says which is which.
    """
    rows = reliability(y, probability, bins=bins)
    total = sum(row["count"] for row in rows)
    if not total:
        return 0.0
    return float(sum(row["count"] * abs(row["predicted"] - row["observed"])
                     for row in rows if row["count"]) / total)


def brier_score(y: np.ndarray, probability: np.ndarray) -> float:
    """Mean squared error of the predicted probabilities.

    Unlike AUC it is a **proper scoring rule**: it is minimised only by
    reporting your true belief, so a model cannot improve it by shading
    its predictions towards the middle or the extremes.

    >>> round(brier_score(np.array([1.0, 0.0]), np.array([1.0, 0.0])), 6)
    0.0
    """
    y = np.asarray(y, dtype=float)
    probability = np.asarray(probability, dtype=float)
    return float(np.mean((probability - y) ** 2))


def brier_decomposition(y: np.ndarray, probability: np.ndarray,
                        bins: int = 10) -> dict:
    """Split the Brier score into reliability, resolution and uncertainty.

        Brier = reliability - resolution + uncertainty

    **Reliability** is the calibration error (lower is better).
    **Resolution** is how far the bins' outcome rates sit from the base
    rate — how much the model actually distinguishes patients (higher is
    better). **Uncertainty** is the base rate's own variance, which no
    model can change.

    The decomposition is the cleanest statement of what this day is
    about: calibration and discrimination are *separate terms*, and a
    model can be good at one while being poor at the other.
    """
    y = np.asarray(y, dtype=float)
    rows = reliability(y, probability, bins=bins)
    total = len(y)
    base_rate = float(y.mean())
    reliability_term = 0.0
    resolution_term = 0.0
    for row in rows:
        if not row["count"]:
            continue
        weight = row["count"] / total
        reliability_term += weight * (row["predicted"] - row["observed"]) ** 2
        resolution_term += weight * (row["observed"] - base_rate) ** 2
    uncertainty = base_rate * (1 - base_rate)
    return {"reliability": reliability_term, "resolution": resolution_term,
            "uncertainty": uncertainty,
            "brier": reliability_term - resolution_term + uncertainty}


def miscalibrate(probability: np.ndarray, power: float = 1.0,
                 shift: float = 0.0) -> np.ndarray:
    """Distort probabilities without changing their order.

    ``power`` raises the odds to a power - over-confident above 1, under
    below - and ``shift`` multiplies the odds by a constant. Both are
    strictly monotone, so **AUC is untouched by construction** and any
    change in calibration is the whole effect.

    This is the instrument for the day's central claim, and the reason it
    is a claim rather than an anecdote.
    """
    probability = np.clip(np.asarray(probability, dtype=float), 1e-12, 1 - 1e-12)
    odds = probability / (1 - probability)
    distorted = np.exp(shift) * odds ** power
    return distorted / (1 + distorted)


def platt_scale(probability: np.ndarray, y: np.ndarray,
                iterations: int = 2000) -> tuple:
    """Fit ``sigmoid(a * logit(p) + b)`` to repair calibration.

    One-dimensional logistic regression on the model's own log-odds. It
    is monotone, so it cannot change the ranking and therefore cannot
    change the AUC - which is exactly the property that makes it a
    calibration fix rather than a new model.
    """
    probability = np.clip(np.asarray(probability, dtype=float), 1e-12, 1 - 1e-12)
    logit = np.log(probability / (1 - probability)).reshape(-1, 1)
    weights, intercept = fit_logistic(logit, np.asarray(y, dtype=float),
                                      iterations=iterations)
    return float(weights[0]), float(intercept)


def apply_platt(probability: np.ndarray, slope: float, intercept: float) -> np.ndarray:
    probability = np.clip(np.asarray(probability, dtype=float), 1e-12, 1 - 1e-12)
    logit = np.log(probability / (1 - probability))
    return sigmoid(slope * logit + intercept)


# --- Day 9 -----------------------------------------------------------------


def drop_mcar(x: np.ndarray, column: int, rate: float = 0.3,
              seed: int = 0) -> np.ndarray:
    """Missing Completely At Random: a coin flip, unrelated to anything.

    The only mechanism under which throwing away incomplete rows is
    unbiased, and the only one that is easy to reason about. It is also
    the one that almost never describes a clinical dataset.
    """
    if not 0 <= rate <= 1:
        raise ValueError(f"rate must be between 0 and 1, got {rate}")
    rng = np.random.default_rng(seed)
    out = x.astype(float).copy()
    out[rng.random(len(x)) < rate, column] = np.nan
    return out


def drop_mar(x: np.ndarray, column: int, driver: int, rate: float = 0.3,
             seed: int = 0) -> np.ndarray:
    """Missing At Random: missingness depends on an OBSERVED feature.

    Cholesterol is measured less often in younger patients, say. The
    missingness is predictable from data you still have, which is what
    makes it recoverable - an imputation that conditions on ``driver``
    can be unbiased, and one that ignores it cannot.
    """
    rng = np.random.default_rng(seed)
    out = x.astype(float).copy()
    strength = (x[:, driver] - x[:, driver].mean()) / (x[:, driver].std() + 1e-12)
    probability = sigmoid(np.log(rate / (1 - rate)) - 1.2 * strength)
    out[rng.random(len(x)) < probability, column] = np.nan
    return out


def drop_mnar(x: np.ndarray, column: int, rate: float = 0.3,
              seed: int = 0) -> np.ndarray:
    """Missing Not At Random: missingness depends on the VALUE that is gone.

    The test was not ordered because the clinician did not expect it to
    be abnormal, so the missing values are systematically the normal
    ones. Nothing in the observed data identifies the bias, because the
    thing that caused it is the thing you do not have.

    No imputation fixes this. The demo does not find one either.
    """
    rng = np.random.default_rng(seed)
    out = x.astype(float).copy()
    values = x[:, column]
    strength = (values - values.mean()) / (values.std() + 1e-12)
    probability = sigmoid(np.log(rate / (1 - rate)) - 1.2 * strength)
    out[rng.random(len(x)) < probability, column] = np.nan
    return out


def complete_cases(x: np.ndarray, y: np.ndarray) -> tuple:
    """Keep only rows with no missing value. The default in most software."""
    keep = ~np.isnan(x).any(axis=1)
    return x[keep], y[keep]


def impute_mean(x: np.ndarray) -> np.ndarray:
    """Replace each missing value with its column's mean.

    The commonest imputation and the one with the clearest failure mode:
    every imputed patient is placed at the centre of the distribution, so
    the column's variance falls. A regression coefficient is a covariance
    over a variance, and shrinking the denominator's spread while adding
    no signal **attenuates the coefficient towards zero** - which the demo
    measures rather than asserts.
    """
    out = x.astype(float).copy()
    for column in range(out.shape[1]):
        missing = np.isnan(out[:, column])
        if missing.any():
            out[missing, column] = float(np.nanmean(out[:, column]))
    return out


def impute_conditional(x: np.ndarray, column: int, drivers) -> np.ndarray:
    """Predict the missing column from the observed ones by least squares.

    The repair for MAR: if missingness depends on features you still
    have, a model conditioning on them can recover the distribution the
    mean destroys.
    """
    out = x.astype(float).copy()
    missing = np.isnan(out[:, column])
    if not missing.any():
        return out
    drivers = list(drivers)
    observed = ~missing
    design = np.column_stack([np.ones(observed.sum()), out[observed][:, drivers]])
    coefficients, *_ = np.linalg.lstsq(design, out[observed, column], rcond=None)
    predict_design = np.column_stack([np.ones(missing.sum()),
                                      out[missing][:, drivers]])
    out[missing, column] = predict_design @ coefficients
    return out


def add_missing_indicator(x: np.ndarray, column: int) -> np.ndarray:
    """Append a 0/1 column recording whether the value was missing.

    Standard advice, and worth being careful about. If missingness is
    informative - a test not ordered because the patient looked well -
    the indicator carries real signal and the model will use it. That
    improves the score on this dataset and encodes the ordering habits of
    one hospital as if they were biology.

    **Call this before imputing, not after.** Imputation fills the NaNs,
    so an indicator built afterwards is a column of zeros: present,
    harmless-looking, and carrying nothing. It raises rather than
    returning that column, because the first version of this day's demo
    made exactly that mistake and the three imputation strategies came
    out with identical coefficients to three decimal places.
    """
    if not np.isnan(x[:, column]).any():
        raise ValueError(
            f"column {column} has no missing values, so the indicator would be "
            "all zeros - add the indicator before imputing, not after")
    indicator = np.isnan(x[:, column]).astype(float).reshape(-1, 1)
    return np.hstack([x, indicator])


def fit_and_score(x: np.ndarray, y: np.ndarray) -> dict:
    """Fit, then report what Level 2 has learned to ask for."""
    weights, intercept = fit_logistic(x, y)
    probability = predict(x, weights, intercept)
    return {"weights": weights, "intercept": intercept,
            "auc": auc(y, probability),
            "ece": expected_calibration_error(y, probability),
            "brier": brier_score(y, probability), "n": len(y)}


#: The cholesterol column of the cohort, which is the one made missing
#: throughout this day.
CHOLESTEROL = 2


def subgroup_report(cohort, imputed: np.ndarray, missing: np.ndarray) -> list:
    """Predictions for the patients whose value survived, and those whose did not.

    The whole point of splitting them: an overall AUC averages the two
    groups and hides the one the imputation invented values for.
    """
    weights, intercept = fit_logistic(imputed, cohort.y)
    probability = predict(imputed, weights, intercept)
    rows = []
    for label, mask in (("value observed", ~missing), ("value missing", missing)):
        rows.append({
            "label": label, "n": int(mask.sum()),
            "true_risk": float(cohort.risk[mask].mean()),
            "predicted": float(probability[mask].mean()),
            "auc": auc(cohort.y[mask], probability[mask]),
        })
    return rows


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every patient here is generated by this file.")

    #: Correlated on purpose. Cholesterol rises with age in any real
    #: cohort, and without that correlation conditional imputation has
    #: nothing to condition on - it becomes mean imputation with extra
    #: steps, which is a finding in itself and is stated below.
    cohort = make_cohort(n=20000, seed=0, prevalence=0.12,
                         correlate_cholesterol=1.5)
    correlation = float(np.corrcoef(cohort.x[:, 0], cohort.x[:, CHOLESTEROL])[0, 1])
    truth = TRUE_COEFFICIENTS["cholesterol_over_5_per_1"]
    complete = fit_and_score(cohort.x, cohort.y)
    print()
    print(f"cohort {len(cohort)}, r(age, cholesterol) = {correlation:.2f}")
    print(f"complete data: cholesterol coefficient "
          f"{complete['weights'][CHOLESTEROL]:.3f}, true {truth}")

    mechanisms = (
        ("MCAR - a coin flip", drop_mcar(cohort.x, CHOLESTEROL, 0.4, seed=1)),
        ("MAR - driven by age", drop_mar(cohort.x, CHOLESTEROL, 0, 0.4, seed=1)),
        ("MNAR - driven by the value", drop_mnar(cohort.x, CHOLESTEROL, 0.4, seed=1)),
    )

    print()
    print("=" * 76)
    print("1. three mechanisms, four ways of coping")
    print("=" * 76)
    for name, damaged in mechanisms:
        missing = np.isnan(damaged[:, CHOLESTEROL])
        print(f"  {name}: {missing.mean():.0%} missing, observed mean "
              f"{np.nanmean(damaged[:, CHOLESTEROL]):+.3f} against a true "
              f"{cohort.x[:, CHOLESTEROL].mean():+.3f}")
        print(f"    {'handling':<26}{'coefficient':>13}{'error':>8}{'AUC':>8}")
        kept_x, kept_y = complete_cases(damaged, cohort.y)
        options = (
            ("complete cases", kept_x, kept_y),
            ("mean imputation", impute_mean(damaged), cohort.y),
            ("conditional imputation",
             impute_conditional(damaged, CHOLESTEROL, [0, 1, 3, 4]), cohort.y),
            ("indicator, then mean",
             impute_mean(add_missing_indicator(damaged, CHOLESTEROL)), cohort.y),
        )
        for label, features, outcomes in options:
            scores = fit_and_score(features, outcomes)
            print(f"    {label:<26}{scores['weights'][CHOLESTEROL]:>13.3f}"
                  f"{abs(scores['weights'][CHOLESTEROL] - truth):>8.3f}"
                  f"{scores['auc']:>8.3f}")
        print()
    print("  mean imputation halves the coefficient under MCAR - 0.162")
    print("  against a true 0.300. Every imputed patient is placed at the")
    print("  centre of the distribution, so the column's spread falls while")
    print("  no signal is added, and a coefficient is a covariance over a")
    print("  variance. Nothing about the data was missing informatively and")
    print("  the estimate is still wrong by more than half.")
    print()
    print("  conditional imputation recovers it in all three rows, and the")
    print("  reason is in the header: age correlates 0.80 with cholesterol")
    print("  here. On a cohort where the other features do not predict the")
    print("  missing one, conditional imputation IS mean imputation with")
    print("  extra steps - measured, on the uncorrelated cohort, as a")
    print("  maximum difference of 0.05 between the two imputed columns.")

    print()
    print("=" * 76)
    print("2. so where does MNAR actually hurt?")
    print("=" * 76)
    print("  the coefficient survived MNAR above. Split the patients by")
    print("  whether their value was kept, and it stops surviving:")
    print()
    for name, damaged in (mechanisms[0], mechanisms[2]):
        missing = np.isnan(damaged[:, CHOLESTEROL])
        imputed = impute_conditional(damaged, CHOLESTEROL, [0, 1, 3, 4])
        print(f"  {name}")
        print(f"    {'group':<20}{'n':>7}{'true risk':>11}{'predicted':>11}{'gap':>8}")
        for row in subgroup_report(cohort, imputed, missing):
            print(f"    {row['label']:<20}{row['n']:>7}{row['true_risk']:>11.3f}"
                  f"{row['predicted']:>11.3f}"
                  f"{row['predicted'] - row['true_risk']:>8.3f}")
        print(f"    imputed cholesterol {imputed[missing, CHOLESTEROL].mean():+.3f} "
              f"against the true hidden {cohort.x[missing, CHOLESTEROL].mean():+.3f}")
        print()
    print("  under MCAR the imputer fills +1.608 where the truth was +1.604.")
    print("  Under MNAR it fills +1.339 where the truth was +0.721.")
    print()
    print("  the missing values were the LOW ones - the test was not ordered")
    print("  because nobody expected it to be abnormal - and no feature in")
    print("  the data says so, because the thing that caused the pattern is")
    print("  the thing that is gone. The imputer therefore invents values")
    print("  that are systematically too high, and the patients it invents")
    print("  them for are over-predicted.")
    print()
    print("  that damage is invisible in the overall coefficient and in the")
    print("  overall AUC. It is visible only when the group is looked at on")
    print("  its own, which is not what a summary table does.")

    print()
    print("=" * 76)
    print("3. and missingness is itself a predictor")
    print("=" * 76)
    print(f"  {'mechanism':<10}{'event rate, missing':>22}"
          f"{'observed':>12}{'indicator coefficient':>24}")
    for name, damaged in (mechanisms[0], mechanisms[2]):
        missing = np.isnan(damaged[:, CHOLESTEROL])
        with_indicator = fit_and_score(
            impute_mean(add_missing_indicator(damaged, CHOLESTEROL)), cohort.y)
        short = name.split(" -")[0]
        print(f"  {short:<10}{cohort.y[missing].mean():>22.1%}"
              f"{cohort.y[~missing].mean():>12.1%}"
              f"{with_indicator['weights'][-1]:>24.3f}")
    print()
    print("  under MNAR the patients with no cholesterol result have an event")
    print("  rate of 8.3% against 15.3% for everybody else. The absence of a")
    print("  test is nearly halving the risk, and a model given the indicator")
    print("  picks that up with a coefficient of -0.14.")
    print()
    print("  this is usually presented as a reason to add the indicator, and")
    print("  it works: the model gets slightly better on this dataset. What")
    print("  it has learned is that THIS hospital orders cholesterol panels")
    print("  when it is worried. Move the model to a hospital that orders")
    print("  them on everybody, and the coefficient is not merely useless -")
    print("  it is applied to a population where it means nothing, with no")
    print("  error and no warning.")
    print()
    print("  the indicator is a good idea and it encodes a fact about a")
    print("  workflow rather than about a patient. Both halves are true and")
    print("  only the first is usually said.")

    print()
    print("=" * 76)
    print("what Level 2 established")
    print("=" * 76)
    print("  Day 5  a coefficient is readable, and reliable only if the")
    print("         cohort is large and the features uncorrelated. Forty")
    print("         honest studies gave age odds ratios from 0.66 to 3.90.")
    print("  Day 6  accuracy measures prevalence. At a 0.9% event rate the")
    print("         model scored 99.1% and found nothing.")
    print("  Day 7  every threshold is an unstated cost ratio, and the ratio")
    print("         moves the cut further than any model change does.")
    print("  Day 8  AUC cannot see calibration at all - four distortions,")
    print("         one AUC to four decimals, a hundredfold range of ECE.")
    print("  Day 9  imputation invents values in the one direction the data")
    print("         cannot reveal, and the harm is invisible in the average.")
    print()
    print("  the through-line: every number in this level is right about")
    print("  something narrower than the question it gets asked. Level 3")
    print("  leaves numbers behind for clinical text, where a single missed")
    print("  identifier is a failure and an average is no comfort at all.")
