"""Day 4 — R-peak detection and heart-rate variability.

A Pan-Tompkins-shaped detector built from Days 2 and 3: band-pass,
square, integrate over a QRS width, threshold against the local level,
then walk back to the tallest raw sample. It is perfect on four of Day
2's five signals, where the fixed threshold managed one.

The day's result is what happens on the fifth. At 92% sensitivity under
motion artefact the heart rate is out by 7% and the SDNN by 680%.

Controlled injection puts a number on it: **one missed beat out of
seventy-two costs 1.4% of the heart rate and 189% of the SDNN** — an
amplification of about 135. The reason is arithmetic. Heart rate is a
count over a duration; a missed beat changes it by one part in
seventy-two. HRV is the spread of the intervals, and a missed beat does
not shorten one interval, it *merges two into one of double the length*,
which then contributes its error squared.

Timing shows the same split from the other side. Jitter of ±48 ms leaves
the heart rate **exactly** right and inflates RMSSD by 27%, while a
constant offset of ten samples costs nothing at all — HRV is computed
from differences, so a bias cancels and only variance survives. The
specification for a detector feeding an HRV measure is not accurate,
precise.

Which is also why the final refinement step is not a free win: it cuts
the offset's standard deviation five-fold under sensor noise and makes
things slightly worse under mains hum, where the raw signal still
carries a ripple that the integrated one does not.

NOT A MEDICAL DEVICE. Every signal in this repo is generated by it.
"""

from __future__ import annotations

import numpy as np

# --- reused from day01 -----------------------------------------------------
# Byte-identical to 01_biosignals/day01_synthetic_ecg/ecg.py.



#: Typical adult resting heart rate, in beats per minute.
DEFAULT_BPM = 72.0

#: Sampling rate in Hz. 250 is a common clinical monitor rate and is
#: comfortably above the Nyquist limit for the ~40 Hz content of a QRS.
DEFAULT_FS = 250.0


def _gaussian(t: np.ndarray, centre: float, width: float, height: float) -> np.ndarray:
    """One smooth bump, used for each of the P, Q, R, S and T deflections."""
    return height * np.exp(-0.5 * ((t - centre) / width) ** 2)


def beat_waveform(fs: float = DEFAULT_FS, duration: float = 0.8) -> np.ndarray:
    """One cardiac cycle, as a sum of five Gaussians.

    The parameters below are shaped to look like lead II: a small upright
    P, a sharp tall R flanked by small negative Q and S, and a broad
    low T. Amplitudes are in millivolts.

    The R peak sits at ``0.25 * duration`` deliberately, leaving room for
    the P wave before it. Day 4's detector must not assume that position.

    >>> wave = beat_waveform(fs=250.0, duration=0.8)
    >>> len(wave)
    200
    """
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if duration <= 0:
        raise ValueError(f"duration must be positive, got {duration}")

    samples = int(round(fs * duration))
    t = np.linspace(0.0, duration, samples, endpoint=False)
    r_time = 0.25 * duration

    wave = np.zeros(samples)
    wave += _gaussian(t, r_time - 0.16, 0.025, 0.12)   # P wave
    wave += _gaussian(t, r_time - 0.02, 0.008, -0.16)  # Q
    wave += _gaussian(t, r_time, 0.010, 1.20)          # R
    wave += _gaussian(t, r_time + 0.02, 0.008, -0.28)  # S
    wave += _gaussian(t, r_time + 0.18, 0.045, 0.30)   # T wave
    return wave


def synthesise_ecg(
    duration: float = 10.0,
    bpm: float = DEFAULT_BPM,
    fs: float = DEFAULT_FS,
    hrv: float = 0.0,
    seed: int = 0,
) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(signal, r_peak_samples)``.

    ``hrv`` is the standard deviation of beat-to-beat interval jitter, in
    seconds. At 0 the rhythm is metronomic, which is unphysiological — a
    real heart never is — so Day 4 uses a non-zero value and Day 1 keeps
    both available to show the difference.

    The returned peak positions are **ground truth**, not an estimate.
    Everything downstream is scored against them.

    >>> signal, peaks = synthesise_ecg(duration=4.0, bpm=60.0, fs=100.0)
    >>> len(signal), len(peaks)
    (400, 4)
    """
    if duration <= 0:
        raise ValueError(f"duration must be positive, got {duration}")
    if bpm <= 0:
        raise ValueError(f"bpm must be positive, got {bpm}")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if hrv < 0:
        raise ValueError(f"hrv must be non-negative, got {hrv}")

    rng = np.random.default_rng(seed)
    total_samples = int(round(duration * fs))
    signal = np.zeros(total_samples)
    peaks: list[int] = []

    mean_interval = 60.0 / bpm
    beat = beat_waveform(fs=fs, duration=mean_interval)
    r_offset = int(round(0.25 * len(beat)))

    time = 0.0
    while True:
        start = int(round(time * fs))
        if start >= total_samples:
            break
        end = min(start + len(beat), total_samples)
        signal[start:end] += beat[: end - start]
        r_position = start + r_offset
        if r_position < total_samples:
            peaks.append(r_position)

        interval = mean_interval
        if hrv > 0:
            interval = max(0.25, mean_interval + rng.normal(0.0, hrv))
        time += interval

    return signal, np.array(peaks, dtype=int)


def heart_rate(peaks: np.ndarray, fs: float = DEFAULT_FS) -> float:
    """Mean heart rate in beats per minute, from R-peak positions.

    Computed from the **intervals**, not from ``len(peaks) / duration``.
    The two differ whenever the recording does not start and end exactly
    on a beat, and the interval form is what a monitor actually reports.

    >>> round(heart_rate(np.array([0, 250, 500, 750]), fs=250.0), 3)
    60.0
    """
    peaks = np.asarray(peaks)
    if peaks.size < 2:
        raise ValueError("need at least two peaks to measure a rate")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    intervals = np.diff(peaks) / fs
    return float(60.0 / intervals.mean())


def rr_intervals(peaks: np.ndarray, fs: float = DEFAULT_FS) -> np.ndarray:
    """Beat-to-beat intervals in seconds — the input to every HRV measure."""
    peaks = np.asarray(peaks)
    if peaks.size < 2:
        raise ValueError("need at least two peaks to measure intervals")
    return np.diff(peaks) / fs


def signal_to_noise(clean: np.ndarray, noisy: np.ndarray) -> float:
    """SNR in decibels, given the clean signal and its corrupted version.

    Only computable because the clean signal exists — which is the whole
    argument for synthesising it. On real data this number is unavailable
    and every filtering claim becomes a matter of opinion.
    """
    clean = np.asarray(clean, dtype=float)
    noisy = np.asarray(noisy, dtype=float)
    if clean.shape != noisy.shape:
        raise ValueError(f"shapes differ: {clean.shape} and {noisy.shape}")
    noise = noisy - clean
    noise_power = float(np.mean(noise ** 2))
    if noise_power == 0:
        return float("inf")
    return float(10.0 * np.log10(np.mean(clean ** 2) / noise_power))


# --- Day 2 -----------------------------------------------------------------


def baseline_wander(signal: np.ndarray, fs: float = DEFAULT_FS,
                    amplitude: float = 0.3, frequency: float = 0.25,
                    seed: int | None = None) -> np.ndarray:
    """Slow drift of the whole trace, mostly from breathing.

    A respiration cycle is 12-20 breaths a minute, so 0.2-0.33 Hz, and
    the chest movement drags the electrode baseline with it. The result
    is the trace wandering up and down the screen while the beats
    themselves are untouched.

    That last part matters for everything downstream: wander moves the
    signal, not the **timing**. A detector that finds peaks by position
    is unaffected; one that compares against a fixed amplitude threshold
    fails completely, and Day 3 measures exactly that difference.

    >>> signal, _ = synthesise_ecg(duration=2.0, fs=100.0)
    >>> noisy = baseline_wander(signal, fs=100.0)
    >>> len(noisy) == len(signal)
    True
    """
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    if frequency <= 0:
        raise ValueError(f"frequency must be positive, got {frequency}")
    time = np.arange(len(signal)) / fs
    phase = 0.0 if seed is None else np.random.default_rng(seed).uniform(0, 2 * np.pi)
    return signal + amplitude * np.sin(2 * np.pi * frequency * time + phase)


def mains_hum(signal: np.ndarray, fs: float = DEFAULT_FS,
              amplitude: float = 0.05, frequency: float = 50.0) -> np.ndarray:
    """Powerline interference: a pure tone at 50 Hz, or 60 Hz in the Americas.

    The frequency is not a detail. A QRS complex has most of its energy
    between 5 and 20 Hz with a tail out past 40, so a 50 Hz notch is
    close to the signal and a 60 Hz notch is a little further away. Day 3
    measures what removing it costs the QRS.

    It is also perfectly periodic, which makes it the one artefact here
    that a filter can remove almost exactly - and the demo shows why that
    is not true of the other two.
    """
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    if frequency <= 0:
        raise ValueError(f"frequency must be positive, got {frequency}")
    if frequency >= fs / 2:
        raise ValueError(
            f"{frequency} Hz is at or above the Nyquist limit for fs={fs}; "
            "it would alias to a lower frequency rather than appear where it is")
    time = np.arange(len(signal)) / fs
    return signal + amplitude * np.sin(2 * np.pi * frequency * time)


def motion_artefact(signal: np.ndarray, fs: float = DEFAULT_FS,
                    bursts: int = 3, amplitude: float = 1.5,
                    width: float = 0.4, seed: int = 0) -> np.ndarray:
    """Short, large excursions from the electrode moving on the skin.

    The hardest of the three to FILTER, and the reason is its shape
    rather than its size: a burst is broad-band and transient, so it
    overlaps the QRS in both frequency and time. There is no band to
    remove that does not also contain the beat, which is Day 3's problem.

    "Hardest to filter" is not the same as "most damaging", and the demo
    measures the difference. At equal signal-to-noise ratio a burst does
    LESS damage to a threshold detector than continuous noise does,
    because it is confined to a few hundred milliseconds while mains hum
    is present at every sample. I had this the wrong way round until the
    equal-SNR table was run.

    Each burst here is a Gaussian envelope over noise, which is a
    caricature of what an electrode does when a patient shifts - and
    enough to produce excursions taller than the R peak, which is the
    property Day 4's detector has to survive.
    """
    if bursts < 0:
        raise ValueError(f"bursts must be non-negative, got {bursts}")
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    rng = np.random.default_rng(seed)
    noisy = signal.astype(float).copy()
    time = np.arange(len(signal)) / fs
    duration = len(signal) / fs
    for _ in range(bursts):
        centre = rng.uniform(0.1 * duration, 0.9 * duration)
        envelope = np.exp(-0.5 * ((time - centre) / width) ** 2)
        noisy += amplitude * envelope * rng.normal(0.0, 1.0, size=len(signal))
    return noisy


def sensor_noise(signal: np.ndarray, amplitude: float = 0.02,
                 seed: int = 0) -> np.ndarray:
    """Broadband white noise from the amplifier and the electrode contact."""
    if amplitude < 0:
        raise ValueError(f"amplitude must be non-negative, got {amplitude}")
    rng = np.random.default_rng(seed)
    return signal + rng.normal(0.0, amplitude, size=len(signal))


def dominant_frequency(signal: np.ndarray, fs: float = DEFAULT_FS,
                       ignore_dc: bool = True) -> float:
    """The frequency carrying the most energy, by FFT.

    Used to show that each artefact sits somewhere different in the
    spectrum - which is what makes two of them filterable and one not.
    """
    spectrum = np.abs(np.fft.rfft(signal))
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    if ignore_dc and len(spectrum) > 1:
        spectrum = spectrum[1:]
        frequencies = frequencies[1:]
    return float(frequencies[int(np.argmax(spectrum))])


def band_energy(signal: np.ndarray, low: float, high: float,
                fs: float = DEFAULT_FS) -> float:
    """Fraction of the signal's energy between ``low`` and ``high`` Hz."""
    if low < 0 or high <= low:
        raise ValueError(f"expected 0 <= low < high, got {low} and {high}")
    spectrum = np.abs(np.fft.rfft(signal)) ** 2
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    total = spectrum.sum()
    if total <= 0:
        return 0.0
    selected = (frequencies >= low) & (frequencies < high)
    return float(spectrum[selected].sum() / total)


def threshold_detect(signal: np.ndarray, threshold: float = 0.5,
                     fs: float = DEFAULT_FS, refractory: float = 0.2) -> np.ndarray:
    """The most naive R-peak detector there is: sample above a fixed level.

    Deliberately bad, and deliberately the obvious first idea. It is here
    so that Day 2 can show which noise breaks it and Day 3 can show what
    filtering repairs — a detector nobody would ship, used as an
    instrument.

    ``refractory`` suppresses repeat detections within 200 ms, because
    the heart physically cannot beat twice that fast and without it every
    R peak counts as a dozen.
    """
    if refractory < 0:
        raise ValueError(f"refractory must be non-negative, got {refractory}")
    above = np.where(signal > threshold)[0]
    if not len(above):
        return np.array([], dtype=int)
    gap = int(round(refractory * fs))
    peaks = [above[0]]
    for index in above[1:]:
        if index - peaks[-1] >= gap:
            peaks.append(index)
    # Within each detected region, take the actual maximum.
    refined = []
    for start in peaks:
        end = min(start + gap, len(signal))
        refined.append(start + int(np.argmax(signal[start:end])))
    return np.array(sorted(set(refined)), dtype=int)


def match_peaks(detected: np.ndarray, truth: np.ndarray,
                tolerance_samples: int = 25) -> dict:
    """Score detections against the ground truth Day 1 wrote down.

    A detection counts if it lands within ``tolerance_samples`` of a true
    peak - 100 ms at 250 Hz, which is about the width of a QRS. Each true
    peak can be matched once, so a detector cannot score twice for
    finding the same beat twice.
    """
    truth = list(truth)
    unmatched = set(range(len(truth)))
    true_positive = 0
    for position in detected:
        best = None
        for index in unmatched:
            if abs(truth[index] - position) <= tolerance_samples:
                if best is None or abs(truth[index] - position) < abs(truth[best] - position):
                    best = index
        if best is not None:
            unmatched.discard(best)
            true_positive += 1
    false_positive = len(detected) - true_positive
    false_negative = len(unmatched)
    sensitivity = true_positive / len(truth) if len(truth) else 0.0
    precision = (true_positive / len(detected)) if len(detected) else 0.0
    return {"true_positive": true_positive, "false_positive": false_positive,
            "false_negative": false_negative, "sensitivity": sensitivity,
            "precision": precision}


def amplitude_for_snr(clean: np.ndarray, make_noisy, target_db: float,
                      low: float = 1e-4, high: float = 20.0,
                      steps: int = 60) -> float:
    """The artefact amplitude that produces a chosen signal-to-noise ratio.

    Bisection, because SNR falls monotonically with amplitude for every
    artefact here. It exists so the demo can compare artefacts at *equal*
    SNR rather than at equal amplitude, which is the only comparison that
    says anything about the artefact rather than about the units.
    """
    for _ in range(steps):
        middle = (low + high) / 2
        if signal_to_noise(clean, make_noisy(middle)) > target_db:
            low = middle
        else:
            high = middle
    return (low + high) / 2


# --- Day 3 -----------------------------------------------------------------


def moving_average(signal: np.ndarray, window: int, causal: bool = False) -> np.ndarray:
    """The simplest low-pass filter there is: the mean of a sliding window.

    ``causal`` decides whether the window looks backwards only (as it
    must in real time, on a monitor, where the future has not happened
    yet) or is centred on the sample (as it may offline, on a recording).

    That flag is the whole of section 2 below. A causal window of ``w``
    samples delays everything by ``(w-1)/2`` samples, which for a 0.6 s
    window at 250 Hz is 300 ms — longer than a QRS complex, and applied
    to a measurement whose entire purpose is timing.

    >>> moving_average(np.array([0.0, 3.0, 0.0]), window=3).round(3)
    array([1.   , 1.   , 1.   ])
    """
    if window < 1:
        raise ValueError(f"window must be at least 1 sample, got {window}")
    if window == 1:
        return signal.astype(float).copy()
    kernel = np.ones(window) / window
    padded = np.pad(signal.astype(float), (window - 1, window - 1), mode="edge")
    smoothed = np.convolve(padded, kernel, mode="valid")
    if causal:
        return smoothed[:len(signal)]
    offset = (window - 1) // 2
    return smoothed[offset:offset + len(signal)]


def remove_baseline(signal: np.ndarray, fs: float = DEFAULT_FS,
                    window_seconds: float = 0.6,
                    causal: bool = False) -> np.ndarray:
    """High-pass by subtraction: signal minus its own slow average.

    A moving average over a window longer than a beat estimates the
    baseline; subtracting it removes the drift. The window length is the
    only knob and it is a genuine trade, measured in the demo: too short
    and the average starts tracking the QRS itself, which subtracts the
    beat away; too long and slower wander survives.
    """
    window = max(1, int(round(window_seconds * fs)))
    return signal - moving_average(signal, window, causal=causal)


def notch_filter(signal: np.ndarray, fs: float = DEFAULT_FS,
                 frequency: float = 50.0, width: float = 2.0) -> np.ndarray:
    """Zero out one narrow band in the spectrum, then transform back.

    Not how a real monitor does it - a biquad IIR notch is cheaper and
    causal - but it isolates the question this day asks: a notch removes
    everything in its band, including whatever the SIGNAL had there, and
    the demo prices that.
    """
    if width <= 0:
        raise ValueError(f"width must be positive, got {width}")
    if frequency <= 0 or frequency >= fs / 2:
        raise ValueError(f"frequency must be between 0 and {fs / 2}, got {frequency}")
    spectrum = np.fft.rfft(signal)
    frequencies = np.fft.rfftfreq(len(signal), d=1.0 / fs)
    spectrum[np.abs(frequencies - frequency) <= width / 2] = 0.0
    return np.fft.irfft(spectrum, n=len(signal))


def peak_amplitude(signal: np.ndarray, peaks: np.ndarray,
                   half_width: int = 10) -> float:
    """Mean height of the signal at the known R-peak positions.

    Measured at the ground-truth positions rather than at detected ones,
    so it reports what the filter did to the beat rather than what it did
    to the detector.
    """
    if not len(peaks):
        return 0.0
    heights = []
    for position in peaks:
        low = max(0, position - half_width)
        high = min(len(signal), position + half_width + 1)
        heights.append(signal[low:high].max())
    return float(np.mean(heights))


def peak_shift(signal: np.ndarray, peaks: np.ndarray,
               search: int = 60) -> float:
    """Mean samples between each true peak and the nearest local maximum.

    A causal filter delays the whole signal, so the beat arrives late.
    This measures by how much, which for a timing measurement is the
    number that matters more than amplitude.
    """
    if not len(peaks):
        return 0.0
    shifts = []
    for position in peaks:
        low = max(0, position - search)
        high = min(len(signal), position + search + 1)
        if high - low < 3:
            continue
        shifts.append(low + int(np.argmax(signal[low:high])) - position)
    return float(np.mean(shifts)) if shifts else 0.0


def adaptive_threshold_detect(signal: np.ndarray, fs: float = DEFAULT_FS,
                              window_seconds: float = 2.0,
                              factor: float = 0.5,
                              refractory: float = 0.2) -> np.ndarray:
    """Threshold against the LOCAL signal level rather than a fixed one.

    Day 2 showed that baseline wander destroys a fixed threshold while
    leaving the timing untouched. This is the repair: the threshold at
    each sample is ``factor`` of the local maximum, estimated over a
    window a few beats long, so drift moves the threshold with the
    signal.

    It is still not a good detector - Day 4 builds that - but it is the
    minimum change that survives the artefact Day 2 identified, and the
    demo measures whether it does.
    """
    if not 0 < factor < 1:
        raise ValueError(f"factor must be between 0 and 1, got {factor}")
    window = max(3, int(round(window_seconds * fs)))
    envelope = moving_average(np.abs(signal), window)
    local = envelope * 0
    half = window // 2
    for index in range(len(signal)):
        low = max(0, index - half)
        high = min(len(signal), index + half + 1)
        local[index] = signal[low:high].max()
    above = np.where(signal > factor * local)[0]
    if not len(above):
        return np.array([], dtype=int)
    gap = int(round(refractory * fs))
    starts = [above[0]]
    for index in above[1:]:
        if index - starts[-1] >= gap:
            starts.append(index)
    refined = []
    for start in starts:
        end = min(start + gap, len(signal))
        refined.append(start + int(np.argmax(signal[start:end])))
    return np.array(sorted(set(refined)), dtype=int)


# --- Day 4 -----------------------------------------------------------------


def bandpass(signal: np.ndarray, fs: float = DEFAULT_FS,
             low_seconds: float = 0.02, high_seconds: float = 0.12) -> np.ndarray:
    """Keep the QRS band by subtracting two moving averages.

    A crude band-pass: smooth lightly to kill high-frequency noise,
    smooth heavily to estimate the baseline, subtract. Day 3 built both
    halves and measured what each costs; this is the combination.
    """
    smoothed = moving_average(signal, max(1, int(round(low_seconds * fs))))
    baseline = moving_average(signal, max(1, int(round(high_seconds * fs))))
    return smoothed - baseline


def integrate(signal: np.ndarray, fs: float = DEFAULT_FS,
              window_seconds: float = 0.15) -> np.ndarray:
    """Square, then average over about a QRS width.

    Squaring makes every deflection positive and exaggerates the tall
    ones, so the QRS stands out from the P and T waves rather than merely
    being the largest of three. Integrating turns the spiky result into
    one broad bump per beat, which is far easier to threshold than a
    spike whose exact peak sample is noise-dependent.
    """
    window = max(1, int(round(window_seconds * fs)))
    return moving_average(signal ** 2, window)


def detect_r_peaks(signal: np.ndarray, fs: float = DEFAULT_FS,
                   refractory: float = 0.2, factor: float = 0.3,
                   window_seconds: float = 2.0) -> np.ndarray:
    """Band-pass, square, integrate, threshold locally, refine.

    The Pan-Tompkins shape, in the smallest form that works: each stage
    above, an adaptive threshold from Day 3, a refractory period, and a
    final step that walks back to the tallest sample of the ORIGINAL
    signal near each detection.

    That last step matters for Day 4's actual subject. The integration
    window smears the beat over 150 ms, so the peak of the integrated
    signal is not where the R peak is. Heart rate survives that error;
    heart-rate variability does not, and the demo shows the difference.
    """
    if not 0 < factor < 1:
        raise ValueError(f"factor must be between 0 and 1, got {factor}")
    filtered = bandpass(signal, fs=fs)
    energy = integrate(filtered, fs=fs)

    window = max(3, int(round(window_seconds * fs)))
    half = window // 2
    threshold = np.empty_like(energy)
    for index in range(len(energy)):
        low = max(0, index - half)
        high = min(len(energy), index + half + 1)
        threshold[index] = factor * energy[low:high].max()

    above = np.where(energy > threshold)[0]
    if not len(above):
        return np.array([], dtype=int)

    gap = int(round(refractory * fs))
    starts = [above[0]]
    for index in above[1:]:
        if index - starts[-1] >= gap:
            starts.append(index)

    search = max(1, int(round(0.05 * fs)))
    peaks = []
    for start in starts:
        end = min(start + gap, len(energy))
        centre = start + int(np.argmax(energy[start:end]))
        low = max(0, centre - search)
        high = min(len(signal), centre + search + 1)
        peaks.append(low + int(np.argmax(signal[low:high])))
    return np.array(sorted(set(peaks)), dtype=int)


def sdnn(peaks: np.ndarray, fs: float = DEFAULT_FS) -> float:
    """Standard deviation of the RR intervals, in milliseconds.

    The most-quoted heart-rate variability number, and the most fragile:
    it is a standard deviation, so one wrong interval contributes its
    error squared.
    """
    if len(peaks) < 3:
        return 0.0        # fewer than two intervals: nothing to spread
    intervals = rr_intervals(peaks, fs=fs)
    return float(np.std(intervals, ddof=1) * 1000.0)


def rmssd(peaks: np.ndarray, fs: float = DEFAULT_FS) -> float:
    """Root mean square of successive RR differences, in milliseconds.

    Sensitive to beat-to-beat change rather than to the overall spread,
    which is why it is preferred for short recordings — and which makes
    it *more* vulnerable to a single misplaced beat, not less: one bad
    peak corrupts two successive differences.
    """
    if len(peaks) < 3:
        return 0.0
    intervals = rr_intervals(peaks, fs=fs)
    differences = np.diff(intervals)
    return float(np.sqrt(np.mean(differences ** 2)) * 1000.0)


def pnn50(peaks: np.ndarray, fs: float = DEFAULT_FS) -> float:
    """Fraction of successive RR differences longer than 50 ms."""
    if len(peaks) < 3:
        return 0.0
    intervals = rr_intervals(peaks, fs=fs)
    differences = np.abs(np.diff(intervals))
    return float(np.mean(differences > 0.05))


def drop_beats(peaks: np.ndarray, count: int = 1, seed: int = 0) -> np.ndarray:
    """Remove ``count`` detections at random. Simulates a missed beat."""
    if count <= 0 or not len(peaks):
        return peaks.copy()
    rng = np.random.default_rng(seed)
    keep = np.ones(len(peaks), dtype=bool)
    interior = np.arange(1, len(peaks) - 1)
    chosen = rng.choice(interior, size=min(count, len(interior)), replace=False)
    keep[chosen] = False
    return peaks[keep]


def add_false_beats(peaks: np.ndarray, count: int = 1, fs: float = DEFAULT_FS,
                    seed: int = 0) -> np.ndarray:
    """Insert ``count`` spurious detections between real ones."""
    if count <= 0 or len(peaks) < 2:
        return peaks.copy()
    rng = np.random.default_rng(seed)
    extra = []
    for _ in range(count):
        index = int(rng.integers(0, len(peaks) - 1))
        midpoint = (peaks[index] + peaks[index + 1]) // 2
        extra.append(midpoint)
    return np.array(sorted(set(peaks.tolist() + extra)), dtype=int)


def jitter_peaks(peaks: np.ndarray, samples: int = 2, seed: int = 0) -> np.ndarray:
    """Move every detection by a few samples. Simulates imprecise timing."""
    if samples <= 0 or not len(peaks):
        return peaks.copy()
    rng = np.random.default_rng(seed)
    moved = peaks + rng.integers(-samples, samples + 1, size=len(peaks))
    return np.array(sorted(set(np.maximum(moved, 0).tolist())), dtype=int)


def detect_unrefined(signal: np.ndarray, fs: float = DEFAULT_FS,
                     refractory: float = 0.2, factor: float = 0.3,
                     window_seconds: float = 2.0) -> np.ndarray:
    """``detect_r_peaks`` stopping at the integrated signal's peak.

    Kept so the demo can price the refinement step rather than assert it
    was needed. The integration window smears each beat over 150 ms, so
    this returns a position near the R peak rather than on it.
    """
    filtered = bandpass(signal, fs=fs)
    energy = integrate(filtered, fs=fs)
    window = max(3, int(round(window_seconds * fs)))
    half = window // 2
    threshold = np.array([
        factor * energy[max(0, i - half):min(len(energy), i + half + 1)].max()
        for i in range(len(energy))])
    above = np.where(energy > threshold)[0]
    if not len(above):
        return np.array([], dtype=int)
    gap = int(round(refractory * fs))
    starts = [above[0]]
    for index in above[1:]:
        if index - starts[-1] >= gap:
            starts.append(index)
    return np.array([s + int(np.argmax(energy[s:min(s + gap, len(energy))]))
                     for s in starts], dtype=int)


def timing_offsets(detected: np.ndarray, truth: np.ndarray) -> np.ndarray:
    """Signed distance from each detection to the nearest true peak."""
    if not len(detected):
        return np.array([])
    return np.array([min((p - t for t in truth), key=abs) for p in detected])


def percent_error(value: float, reference: float) -> float:
    if reference == 0:
        return 0.0
    return abs(value - reference) / reference * 100.0


if __name__ == "__main__":
    import sys

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - platform dependent
        pass

    print("NOT A MEDICAL DEVICE. Every signal here is generated by this file.")
    print()

    clean, truth = synthesise_ecg(duration=60.0, hrv=0.04, seed=0)
    true_hr, true_sdnn, true_rmssd = heart_rate(truth), sdnn(truth), rmssd(truth)
    print(f"60 s, {len(truth)} beats, beat-to-beat jitter injected at 40 ms")
    print(f"ground truth: HR {true_hr:.1f} bpm, SDNN {true_sdnn:.1f} ms, "
          f"RMSSD {true_rmssd:.1f} ms")

    print()
    print("=" * 72)
    print("1. a detector that survives Day 2's artefacts")
    print("=" * 72)
    print("  band-pass, square, integrate over a QRS width, threshold against")
    print("  the local level, then walk back to the tallest sample of the")
    print("  original signal. Every stage was built on Days 2 and 3.")
    print()
    print(f"  {'signal':<20}{'sens':>7}{'prec':>7}{'HR bpm':>9}"
          f"{'SDNN ms':>10}{'RMSSD ms':>10}")
    print(f"  {'ground truth':<20}{'-':>7}{'-':>7}{true_hr:>9.1f}"
          f"{true_sdnn:>10.1f}{true_rmssd:>10.1f}")
    signals = (
        ("clean", clean),
        ("baseline wander", baseline_wander(clean, amplitude=0.4)),
        ("mains hum", mains_hum(clean, amplitude=0.3)),
        ("sensor noise", sensor_noise(clean, amplitude=0.05)),
        ("motion artefact", motion_artefact(clean, amplitude=1.5, seed=1)),
    )
    for name, signal in signals:
        detected = detect_r_peaks(signal)
        scores = match_peaks(detected, truth)
        print(f"  {name:<20}{scores['sensitivity']:>7.0%}{scores['precision']:>7.0%}"
              f"{heart_rate(detected):>9.1f}{sdnn(detected):>10.1f}"
              f"{rmssd(detected):>10.1f}")
    print()
    print("  four of five are perfect, which Day 2's fixed threshold managed")
    print("  on one. Motion artefact still breaks it - and look at what")
    print("  breaks: the heart rate is out by 7% and the SDNN by 680%.")

    print()
    print("=" * 72)
    print("2. heart rate is robust. Heart-rate variability is not.")
    print("=" * 72)
    print("  one controlled error at a time, against a perfect detection:")
    print()
    print(f"  {'error injected':<24}{'beats':>7}{'HR err':>9}"
          f"{'SDNN err':>11}{'RMSSD err':>11}")
    cases = [("none", truth)]
    for count in (1, 2, 4):
        cases.append((f"{count} beat(s) missed", drop_beats(truth, count, seed=1)))
    for count in (1, 2, 4):
        cases.append((f"{count} false beat(s)", add_false_beats(truth, count, seed=1)))
    for jitter in (1, 3, 6):
        cases.append((f"timing jitter +/-{jitter}", jitter_peaks(truth, jitter, seed=1)))
    for name, peaks in cases:
        print(f"  {name:<24}{len(peaks):>7}"
              f"{percent_error(heart_rate(peaks), true_hr):>8.1f}%"
              f"{percent_error(sdnn(peaks), true_sdnn):>10.1f}%"
              f"{percent_error(rmssd(peaks), true_rmssd):>10.1f}%")
    print()
    print("  one missed beat out of seventy-two - a detector at 98.6%")
    print("  sensitivity - costs 1.4% of the heart rate and 189% of the")
    print("  SDNN. That is an amplification of about 135 times.")
    print()
    print("  the reason is arithmetic rather than physiology. Heart rate is")
    print("  a count over a duration, so losing one beat of seventy-two")
    print("  changes it by one part in seventy-two. HRV is the spread of the")
    print("  intervals, and a missed beat does not shorten an interval - it")
    print("  MERGES two into one of double the length, which is then far")
    print("  outside the distribution and contributes its error squared.")
    print()
    print("  so a detector good enough to report a pulse is nowhere near")
    print("  good enough to report variability, and the sensitivity figure")
    print("  does not tell you which you have.")

    print()
    print("=" * 72)
    print("3. what timing precision costs, and what it does not")
    print("=" * 72)
    print("  the jitter rows above find no beats wrongly and miss none. Every")
    print("  beat is detected, a few samples off:")
    print()
    print(f"  {'jitter':<20}{'ms':>7}{'HR err':>9}{'SDNN err':>11}{'RMSSD err':>11}")
    for jitter in (1, 3, 6, 12):
        peaks = jitter_peaks(truth, jitter, seed=1)
        print(f"  {f'+/-{jitter} samples':<20}{jitter / DEFAULT_FS * 1000:>7.0f}"
              f"{percent_error(heart_rate(peaks), true_hr):>8.1f}%"
              f"{percent_error(sdnn(peaks), true_sdnn):>10.1f}%"
              f"{percent_error(rmssd(peaks), true_rmssd):>10.1f}%")
    print()
    print("  the heart rate is EXACTLY right at every level of jitter,")
    print("  because the first and last beats have not moved much and the")
    print("  count has not changed at all. RMSSD is out by 27% at 48 ms.")
    print()
    print("  and a constant offset costs nothing whatsoever:")
    shifted = truth + 10
    print(f"    every peak moved +10 samples: HR err "
          f"{percent_error(heart_rate(shifted), true_hr):.1f}%, "
          f"SDNN err {percent_error(sdnn(shifted), true_sdnn):.1f}%, "
          f"RMSSD err {percent_error(rmssd(shifted), true_rmssd):.1f}%")
    print()
    print("  HRV is computed from DIFFERENCES between intervals, so a bias")
    print("  cancels and only the variance of the error survives. That is")
    print("  the specification for a peak detector feeding an HRV measure:")
    print("  not accurate, precise.")

    print()
    print("=" * 72)
    print("4. so does the refinement step earn its place?")
    print("=" * 72)
    print("  the integration window smears each beat over 150 ms, so the")
    print("  integrated peak is near the R peak rather than on it. The last")
    print("  stage walks back to the tallest raw sample. Section 3 says that")
    print("  should only matter if it reduces the VARIANCE of the offset.")
    print()
    print(f"  {'signal':<16}{'variant':<20}{'mean off':>10}{'sd off':>9}"
          f"{'SDNN err':>11}{'RMSSD err':>11}")
    for label, signal in (("clean", clean),
                          ("sensor noise", sensor_noise(clean, amplitude=0.08)),
                          ("mains hum", mains_hum(clean, amplitude=0.3))):
        for variant, detected in (("integrated only", detect_unrefined(signal)),
                                  ("refined", detect_r_peaks(signal))):
            offsets = timing_offsets(detected, truth)
            print(f"  {label:<16}{variant:<20}{offsets.mean():>10.2f}"
                  f"{offsets.std():>9.2f}"
                  f"{percent_error(sdnn(detected), true_sdnn):>10.1f}%"
                  f"{percent_error(rmssd(detected), true_rmssd):>10.1f}%")
    print()
    print("  on the clean signal it removes a constant one-sample offset and")
    print("  changes the HRV by nothing at all - exactly as section 3")
    print("  predicted a bias would.")
    print()
    print("  on sensor noise it cuts the offset's standard deviation from")
    print("  2.35 samples to 0.49 and the RMSSD error from 7.6% to 1.4%.")
    print("  That is the case it was written for.")
    print()
    print("  on mains hum it makes things slightly WORSE - the integrated")
    print("  signal is smooth and stable, while the raw signal still carries")
    print("  a 50 Hz ripple that moves the local maximum around. The step is")
    print("  not a free win, and a detector that always refines is making an")
    print("  assumption about its noise.")

    print()
    print("=" * 72)
    print("what Level 1 established")
    print("=" * 72)
    print("  Day 1  a signal with exact ground truth, because a public")
    print("         database's annotations are estimates too")
    print("  Day 2  SNR does not predict damage - at equal noise power,")
    print("         precision ran from 28% to 80% depending on the artefact")
    print("  Day 3  the filter costs what the beat needed, and two of three")
    print("         artefacts were better answered by a better detector")
    print("  Day 4  heart rate survives a mediocre detector and variability")
    print("         does not, by a factor of about 135")
    print()
    print("  the through-line is that a number can be right for a reason")
    print("  that does not survive contact with the next measurement. Level")
    print("  2 leaves signals behind and starts scoring risk, where the same")
    print("  problem appears as a model with excellent accuracy and no")
    print("  clinical value whatsoever.")
